// Auto-generated from free-agency agent output on 2026-03-11
const FA_FLAGS = {
  "ARI": ["Isaac Seumalo", "Roy Lopez", "Kendrick Bourne", "Tyler Allgeier", "Gardner Minshew", "Andrew Wingard", "Matt Pryor", "Elijah Wilkinson", "Jonah Williams", "Casey Kreiter"],
  "ATL": ["Tua Tagovailoa", "Jahan Dotson", "Olamide Zaccheaus", "Austin Hooper", "Azeez Ojulari", "Samson Ebukam", "Cameron Thomas", "Christian Harris", "Channing Tindall", "Chris Williams", "Corey Levin", "Nick Folk", "Jake Bailey"],
  "BAL": ["Trey Hendrickson", "John Simpson", "Jaylinn Hawkins", "Durham Smythe", "Jovaughn Gwyn"],
  "BUF": ["DJ Moore", "Bradley Chubb", "Dee Alford", "Kyle Allen"],
  "CAR": ["Jaelan Phillips", "Devin Lloyd", "Kenny Pickett", "Luke Fortner", "Stone Forsythe", "John Metchie III"],
  "CHI": ["Garrett Bradbury", "Coby Bryant", "Devin Bush", "Neville Gallimore", "Kalif Raymond", "Cam Lewis", "Kentavius Street", "Jedrick Wills Jr."],
  "CIN": ["Boye Mafe", "Bryan Cook", "Jonathan Allen"],
  "CLE": ["Tytus Howard", "Zion Johnson", "Elgton Jenkins", "Quincy Williams", "Jack Stoll"],
  "DAL": ["Rashan Gary", "Jalen Thompson", "P.J. Locke", "Otito Ogbonnia", "Sam Howell"],
  "DEN": ["Jaylen Waddle"],
  "DET": ["Cade Mays", "Juice Scruggs", "Larry Borom", "Isiah Pacheco", "Teddy Bridgewater", "Rock Ya-Sin", "Christian Izien"],
  "GB": ["Zaire Franklin", "Javon Hargrave", "Benjamin St-Juste", "Skyy Moore", "Andre Dillard"],
  "HOU": ["Braden Smith", "David Montgomery", "Reed Blankenship", "Dominique Robinson", "Foster Moreau", "Logan Hall", "Kai Kroeger", "Michael Thomas"],
  "IND": ["Arden Key", "Micheal Clemons", "Colby Wooden", "Derrick Nnadi"],
  "JAX": ["Chris Rodriguez Jr.", "Jakobi Meyers"],
  "KC": ["Kenneth Walker III", "Alohi Gilman", "Khyiris Tonga", "Kader Kohou", "Emari Demercado"],
  "LAC": ["Tyler Biadasz", "Cole Strange", "Charlie Kolar", "Alec Ingold", "Keaton Mitchell"],
  "LAR": ["Trent McDuffie", "Jaylen Watson", "Joe Cardona"],
  "LV": ["Tyler Linderbaum", "Taron Johnson", "Kwity Paye", "Nakobe Dean", "Quay Walker", "Jalen Nailor", "Matt Gay"],
  "MIA": ["Malik Willis", "Josh Uche", "Robert Beal Jr.", "Ben Sims", "Tutu Atwell", "Darrell Baker Jr.", "Alex Austin", "Marco Wilson", "Lonnie Johnson Jr.", "Zayne Anderson", "Zane Gonzalez"],
  "MIN": ["Kyler Murray", "James Pierre"],
  "NE": ["Romeo Doubs", "Alijah Vera-Tucker", "Dre'Mont Jones", "Kevin Byard", "Reggie Gilliam", "Julian Hill", "Mike Brown", "K.J. Britt", "Jesse Luketa"],
  "NO": ["David Edwards", "Travis Etienne Jr.", "Kaden Elliss", "Noah Fant", "Ryan Wright"],
  "NYG": ["Isaiah Likely", "Tremaine Edmunds", "Greg Newsome II", "Patrick Ricard", "Ar'Darius Washington", "Jordan Stout", "Jason Sanders", "Calvin Austin III"],
  "NYJ": ["Minkah Fitzpatrick", "Joseph Ossai", "Kingsley Enagbare", "Demario Davis", "David Onyemata", "T'Vondre Sweat", "Geno Smith", "Dane Belton", "Nahshon Wright", "Dylan Parham", "Austin Schlottmann", "Cade York"],
  "PHI": ["Riq Woolen (Tariq Woolen)", "Johnny Mundt"],
  "PIT": ["Michael Pittman Jr.", "Jamel Dean", "Rico Dowdle", "Jaquan Brisker", "Darnell Savage", "Cameron Johnston"],
  "SEA": ["Emanuel Wilson", "Rodney Thomas II", "D'Anthony Bell"],
  "SF": ["Mike Evans", "Osa Odighizuwa", "Dre Greenlaw", "Vederian Lowe", "Brett Toth", "Nate Hobbs"],
  "TB": ["Alex Anzalone", "A'Shawn Robinson", "Kenneth Gainwell", "Al-Quadin Muhammad", "Jake Browning", "Miles Killebrew"],
  "TEN": ["Wan'Dale Robinson", "Cor'Dale Flott", "Alontae Taylor", "John Franklin-Myers", "Jermaine Johnson II", "Jacob Martin", "Jordan Elliott", "Solomon Thomas", "Daniel Bellinger", "Austin Schlottmann", "Cordell Volson", "Joshua Williams", "Mitchell Trubisky", "Tommy Townsend", "Corey Herring", "Darius Adams"],
  "WSH": ["Odafe Oweh", "K'Lavon Chaisson", "Charles Omenihu", "Leo Chenal", "Tim Settle", "Amik Robertson", "Nick Cross", "Chig Okonkwo", "Rachaad White", "Nick Allegretti", "Jake Moody"],
};
export default FA_FLAGS;
