// Auto-generated from free-agency agent output on 2026-03-11
const FA_FLAGS = {
  "ARI": ["Isaac Seumalo", "Matt Pryor", "Tyler Allgeier", "Kendrick Bourne", "Gardner Minshew", "Roy Lopez"],
  "ATL": ["Tua Tagovailoa", "Jahan Dotson", "Olamide Zaccheaus", "Austin Hooper", "Cameron Thomas", "Christian Harris", "Nick Folk", "Jake Bailey"],
  "BAL": ["John Simpson"],
  "BUF": ["DJ Moore", "Dee Alford", "Kyle Allen"],
  "CAR": ["Jaelan Phillips", "Devin Lloyd", "Kenny Pickett", "Luke Fortner", "Stone Forsythe"],
  "CHI": ["Garrett Bradbury", "Coby Bryant", "Devin Bush", "Neville Gallimore", "Kalif Raymond", "Cameron Lewis", "Kentavius Street"],
  "CIN": ["Boye Mafe", "Bryan Cook"],
  "CLE": ["Tytus Howard", "Zion Johnson", "Elgton Jenkins", "Quincy Williams"],
  "DAL": ["Rashan Gary", "Jalen Thompson", "P.J. Locke", "Otito Ogbonnia"],
  "DET": ["Cade Mays", "Juice Scruggs", "Larry Borom", "Isiah Pacheco", "Teddy Bridgewater"],
  "GB": ["Zaire Franklin", "Benjamin St-Juste", "Skyy Moore"],
  "HOU": ["David Montgomery", "Reed Blankenship", "Braden Smith", "Dominique Robinson", "Logan Hall", "Kai Kroeger"],
  "IND": ["Arden Key", "Colby Wooden", "Corey Ballentine"],
  "JAX": ["Jakobi Meyers"],
  "KC": ["Kenneth Walker III", "Alohi Gilman", "Khyiris Tonga"],
  "LAC": ["Tyler Biadasz", "Cole Strange", "Charlie Kolar", "Alec Ingold"],
  "LAR": ["Trent McDuffie", "Jaylen Watson", "Joe Cardona"],
  "LV": ["Tyler Linderbaum", "Taron Johnson", "Kwity Paye", "Nakobe Dean", "Quay Walker", "Jalen Nailor", "Matt Gay"],
  "MIA": ["Malik Willis", "Zane Gonzalez"],
  "MIN": ["James Pierre"],
  "NE": ["Romeo Doubs", "Alijah Vera-Tucker", "Dre'Mont Jones", "Reggie Gilliam", "Jesse Luketa"],
  "NO": ["Travis Etienne Jr.", "David Edwards", "Noah Fant", "Kaden Elliss", "Ryan Wright", "John Ridgeway"],
  "NYG": ["Tremaine Edmunds", "Isaiah Likely", "Greg Newsome II", "Patrick Ricard", "Jordan Stout", "Ar'Darius Washington", "Emmanuel Sanders"],
  "NYJ": ["T'Vondre Sweat", "Minkah Fitzpatrick", "Geno Smith", "Joseph Ossai", "Kingsley Enagbare", "Demario Davis", "David Onyemata", "Nahshon Wright", "Dane Belton"],
  "PHI": ["Riq Woolen", "Johnny Mundt"],
  "PIT": ["Michael Pittman Jr.", "Jamel Dean", "Rico Dowdle", "Cameron Johnston"],
  "SEA": ["Drew Lock", "D'Anthony Bell", "Eric Saubert", "River Cracraft", "Steven Sims"],
  "SF": ["Mike Evans", "Vederian Lowe"],
  "TB": ["Alex Anzalone", "Kenneth Gainwell"],
  "TEN": ["Jermaine Johnson II", "John Franklin-Myers", "Wan'Dale Robinson", "Alontae Taylor", "Cor'Dale Flott", "Joshua Williams", "Daniel Bellinger", "Mitchell Trubisky", "Austin Schlottman", "Cordell Volson", "Jordan Elliott", "Tommy Townsend"],
  "WSH": ["Odafe Oweh", "Amik Robertson", "Tim Settle", "Leo Chenal"],
};
export default FA_FLAGS;
