// Auto-generated from free-agency agent output on 2026-03-10
const FA_FLAGS = {
  "ARI": ["Isaac Seumalo", "Gardner Minshew", "Tyler Allgeier", "Roy Lopez", "Kendrick Bourne"],
  "ATL": ["Tua Tagovailoa", "Jahan Dotson", "Olamide Zaccheaus", "Austin Hooper", "Cameron Thomas", "Christian Harris", "Nick Folk", "Jake Bailey"],
  "BAL": ["Maxx Crosby", "John Simpson"],
  "BUF": ["DJ Moore", "Dee Alford", "Kyle Allen"],
  "CAR": ["Jaelan Phillips", "Devin Lloyd", "Kenny Pickett"],
  "CHI": ["Coby Bryant", "Devin Bush", "Neville Gallimore", "Garrett Bradbury"],
  "CIN": ["Boye Mafe", "Bryan Cook"],
  "CLE": ["Tytus Howard", "Zion Johnson", "Quincy Williams"],
  "DAL": ["Rashan Gary", "Jalen Thompson"],
  "DET": ["Cade Mays", "Juice Scruggs", "Larry Borom"],
  "GB": ["Zaire Franklin"],
  "HOU": ["Reed Blankenship", "David Montgomery"],
  "IND": ["Arden Key", "Colby Wooden"],
  "KC": ["Kenneth Walker III", "Alohi Gilman", "Khyiris Tonga"],
  "LAC": ["Tyler Biadasz", "Charlie Kolar", "Alec Ingold", "Cole Strange"],
  "LAR": ["Trent McDuffie", "Jaylen Watson", "Joe Cardona"],
  "LV": ["Tyler Linderbaum", "Kwity Paye", "Taron Johnson", "Nakobe Dean", "Quay Walker", "Jalen Nailor", "Matt Gay"],
  "MIA": ["Malik Willis"],
  "MIN": ["James Pierre"],
  "NE": ["Dre'Mont Jones", "Alijah Vera-Tucker", "Reggie Gilliam", "Jesse Luketa"],
  "NO": ["Travis Etienne Jr.", "David Edwards", "Ryan Wright", "Noah Fant", "John Ridgeway"],
  "NYG": ["Isaiah Likely", "Tremaine Edmunds", "Jordan Stout", "Ar'Darius Washington"],
  "NYJ": ["Minkah Fitzpatrick", "Dane Belton", "Joseph Ossai", "Kingsley Enagbare", "T'Vondre Sweat", "David Onyemata", "Demario Davis"],
  "PHI": ["Adoree' Jackson"],
  "PIT": ["Michael Pittman Jr.", "Jamel Dean", "Rico Dowdle"],
  "SEA": ["D'Anthony Bell", "Drew Lock", "Eric Saubert", "Steven Sims", "River Cracraft"],
  "SF": ["Mike Evans", "Vederian Lowe"],
  "TB": ["Kenneth Gainwell", "Alex Anzalone", "Connor Bazelak"],
  "TEN": ["Jermaine Johnson", "John Franklin-Myers", "Wan'Dale Robinson", "Alontae Taylor", "Cor'Dale Flott", "Joshua Williams", "Daniel Bellinger", "Mitchell Trubisky", "Austin Schlottman", "Cordell Volson"],
  "WSH": ["Odafe Oweh", "Tim Settle", "Amik Robertson"],
};
export default FA_FLAGS;
