// 2026 March Madness - 68 teams with analytics
// Source: Sports Reference 2025-26 ratings + advanced stats

export const MARCH_MADNESS_TEAMS = [
  {
    "team": "Duke",
    "seed": 1,
    "region": "East",
    "record": "32-2",
    "conf": "ACC",
    "srsRank": 2,
    "ortg": 129.41,
    "drtg": 84.93,
    "netRtg": 44.48,
    "sos": 13.12,
    "srs": 31.57,
    "pace": 67.1,
    "ftr": 0.378,
    "threePAr": 0.444,
    "tovPct": 13.3,
    "orbPct": 38.1
  },
  {
    "team": "UConn",
    "seed": 2,
    "region": "East",
    "record": "29-5",
    "conf": "Big East",
    "srsRank": 13,
    "ortg": 122.37,
    "drtg": 90.07,
    "netRtg": 32.3,
    "sos": 7.57,
    "srs": 22.93,
    "pace": 66.0,
    "ftr": 0.3,
    "threePAr": 0.403,
    "tovPct": 14.3,
    "orbPct": 35.7
  },
  {
    "team": "Michigan State",
    "seed": 3,
    "region": "East",
    "record": "25-7",
    "conf": "Big Ten",
    "srsRank": 10,
    "ortg": 123.85,
    "drtg": 90.49,
    "netRtg": 33.36,
    "sos": 9.64,
    "srs": 23.46,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Kansas",
    "seed": 4,
    "region": "East",
    "record": "23-10",
    "conf": "Big 12",
    "srsRank": 21,
    "ortg": 119.13,
    "drtg": 89.89,
    "netRtg": 29.24,
    "sos": 8.69,
    "srs": 21.11,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "St. John's",
    "seed": 5,
    "region": "East",
    "record": "28-6",
    "conf": "Big East",
    "srsRank": 15,
    "ortg": 119.9,
    "drtg": 89.84,
    "netRtg": 30.06,
    "sos": 11.75,
    "srs": 22.43,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Louisville",
    "seed": 6,
    "region": "East",
    "record": "23-10",
    "conf": "ACC",
    "srsRank": 11,
    "ortg": 125.72,
    "drtg": 94.12,
    "netRtg": 31.6,
    "sos": 15.05,
    "srs": 23.42,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "UCLA",
    "seed": 7,
    "region": "East",
    "record": "23-11",
    "conf": "Big Ten",
    "srsRank": 29,
    "ortg": 123.71,
    "drtg": 98.06,
    "netRtg": 25.65,
    "sos": 8.4,
    "srs": 18.28,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Ohio State",
    "seed": 8,
    "region": "East",
    "record": "21-12",
    "conf": "Big Ten",
    "srsRank": 27,
    "ortg": 125.4,
    "drtg": 98.86,
    "netRtg": 26.54,
    "sos": 11.46,
    "srs": 19.1,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "TCU",
    "seed": 9,
    "region": "East",
    "record": "22-11",
    "conf": "Big 12",
    "srsRank": 43,
    "ortg": 116.01,
    "drtg": 94.43,
    "netRtg": 21.58,
    "sos": 7.03,
    "srs": 15.77,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "UCF",
    "seed": 10,
    "region": "East",
    "record": "21-11",
    "conf": "Big 12",
    "srsRank": 51,
    "ortg": 120.31,
    "drtg": 102.5,
    "netRtg": 17.81,
    "sos": 11.38,
    "srs": 13.32,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "South Florida",
    "seed": 11,
    "region": "East",
    "record": "24-8",
    "conf": "American",
    "srsRank": 55,
    "ortg": 116.15,
    "drtg": 99.03,
    "netRtg": 17.12,
    "sos": 13.07,
    "srs": 12.98,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Northern Iowa",
    "seed": 12,
    "region": "East",
    "record": "23-12",
    "conf": "MVC",
    "srsRank": 89,
    "ortg": 108.99,
    "drtg": 96.61,
    "netRtg": 12.38,
    "sos": -5.01,
    "srs": 8.52,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Cal Baptist",
    "seed": 13,
    "region": "East",
    "record": "25-8",
    "conf": "WAC",
    "srsRank": 999,
    "ortg": 107.4,
    "drtg": 98.5,
    "netRtg": 8.9,
    "sos": -2.0,
    "srs": 5.5,
    "pace": 67.5,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "North Dakota State",
    "seed": 14,
    "region": "East",
    "record": "24-9",
    "conf": "Summit",
    "srsRank": 999,
    "ortg": 108.2,
    "drtg": 99.1,
    "netRtg": 9.1,
    "sos": -6.5,
    "srs": 3.8,
    "pace": 66.8,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Furman",
    "seed": 15,
    "region": "East",
    "record": "22-12",
    "conf": "SoCon",
    "srsRank": 999,
    "ortg": 106.5,
    "drtg": 101.2,
    "netRtg": 5.3,
    "sos": -4.2,
    "srs": 1.5,
    "pace": 68.1,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Siena",
    "seed": 16,
    "region": "East",
    "record": "23-11",
    "conf": "MAAC",
    "srsRank": 999,
    "ortg": 105.8,
    "drtg": 102.5,
    "netRtg": 3.3,
    "sos": -7.1,
    "srs": -1.0,
    "pace": 67.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Florida",
    "seed": 1,
    "region": "South",
    "record": "26-7",
    "conf": "SEC",
    "srsRank": 4,
    "ortg": 125.71,
    "drtg": 88.39,
    "netRtg": 37.32,
    "sos": 16.0,
    "srs": 27.92,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Houston",
    "seed": 2,
    "region": "South",
    "record": "28-6",
    "conf": "Big 12",
    "srsRank": 7,
    "ortg": 124.21,
    "drtg": 86.6,
    "netRtg": 37.61,
    "sos": 7.19,
    "srs": 26.23,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Illinois",
    "seed": 3,
    "region": "South",
    "record": "24-8",
    "conf": "Big Ten",
    "srsRank": 6,
    "ortg": 132.18,
    "drtg": 94.31,
    "netRtg": 37.87,
    "sos": 15.5,
    "srs": 26.46,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Nebraska",
    "seed": 4,
    "region": "South",
    "record": "26-6",
    "conf": "Big Ten",
    "srsRank": 20,
    "ortg": 119.58,
    "drtg": 89.33,
    "netRtg": 30.25,
    "sos": 7.59,
    "srs": 21.54,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Vanderbilt",
    "seed": 5,
    "region": "South",
    "record": "26-7",
    "conf": "SEC",
    "srsRank": 12,
    "ortg": 126.87,
    "drtg": 95.83,
    "netRtg": 31.04,
    "sos": 15.89,
    "srs": 23.18,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "North Carolina",
    "seed": 6,
    "region": "South",
    "record": "24-8",
    "conf": "ACC",
    "srsRank": 26,
    "ortg": 121.01,
    "drtg": 94.85,
    "netRtg": 26.16,
    "sos": 10.42,
    "srs": 19.4,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "St. Mary's",
    "seed": 7,
    "region": "South",
    "record": "27-5",
    "conf": "WCC",
    "srsRank": 32,
    "ortg": 120.41,
    "drtg": 94.52,
    "netRtg": 25.89,
    "sos": 5.71,
    "srs": 17.91,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Clemson",
    "seed": 8,
    "region": "South",
    "record": "24-10",
    "conf": "ACC",
    "srsRank": 37,
    "ortg": 118.33,
    "drtg": 94.46,
    "netRtg": 23.87,
    "sos": 3.65,
    "srs": 17.0,
    "pace": 65.5,
    "ftr": 0.371,
    "threePAr": 0.429,
    "tovPct": 12.5,
    "orbPct": 28.1
  },
  {
    "team": "Iowa",
    "seed": 9,
    "region": "South",
    "record": "21-12",
    "conf": "Big Ten",
    "srsRank": 28,
    "ortg": 123.9,
    "drtg": 96.65,
    "netRtg": 27.25,
    "sos": 5.64,
    "srs": 19.0,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Texas A&M",
    "seed": 10,
    "region": "South",
    "record": "21-11",
    "conf": "SEC",
    "srsRank": 38,
    "ortg": 120.76,
    "drtg": 99.44,
    "netRtg": 21.32,
    "sos": 15.11,
    "srs": 16.77,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "VCU",
    "seed": 11,
    "region": "South",
    "record": "26-7",
    "conf": "A-10",
    "srsRank": 53,
    "ortg": 118.56,
    "drtg": 101.04,
    "netRtg": 17.52,
    "sos": 9.27,
    "srs": 13.1,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "McNeese",
    "seed": 12,
    "region": "South",
    "record": "28-5",
    "conf": "Southland",
    "srsRank": 91,
    "ortg": 113.07,
    "drtg": 102.0,
    "netRtg": 11.07,
    "sos": 2.54,
    "srs": 7.78,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Troy",
    "seed": 13,
    "region": "South",
    "record": "22-11",
    "conf": "Sun Belt",
    "srsRank": 999,
    "ortg": 110.5,
    "drtg": 103.8,
    "netRtg": 6.7,
    "sos": -2.8,
    "srs": 5.8,
    "pace": 70.2,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Penn",
    "seed": 14,
    "region": "South",
    "record": "18-11",
    "conf": "Ivy",
    "srsRank": 999,
    "ortg": 108.0,
    "drtg": 105.2,
    "netRtg": 2.8,
    "sos": -5.5,
    "srs": -0.4,
    "pace": 67.3,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Idaho",
    "seed": 15,
    "region": "South",
    "record": "21-14",
    "conf": "Big Sky",
    "srsRank": 999,
    "ortg": 104.2,
    "drtg": 103.8,
    "netRtg": 0.4,
    "sos": -8.0,
    "srs": 0.6,
    "pace": 68.5,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Prairie View A&M",
    "seed": 16,
    "region": "South",
    "record": "19-14",
    "conf": "SWAC",
    "srsRank": 999,
    "ortg": 100.5,
    "drtg": 105.8,
    "netRtg": -5.3,
    "sos": -12.0,
    "srs": -5.9,
    "pace": 71.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Arizona",
    "seed": 1,
    "region": "West",
    "record": "32-2",
    "conf": "Big 12",
    "srsRank": 3,
    "ortg": 126.7,
    "drtg": 85.92,
    "netRtg": 40.78,
    "sos": 16.88,
    "srs": 29.93,
    "pace": 71.3,
    "ftr": 0.429,
    "threePAr": 0.268,
    "tovPct": 12.9,
    "orbPct": 38.1
  },
  {
    "team": "Purdue",
    "seed": 2,
    "region": "West",
    "record": "26-8",
    "conf": "Big Ten",
    "srsRank": 8,
    "ortg": 132.11,
    "drtg": 96.1,
    "netRtg": 36.01,
    "sos": 13.29,
    "srs": 25.22,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Gonzaga",
    "seed": 3,
    "region": "West",
    "record": "30-3",
    "conf": "WCC",
    "srsRank": 9,
    "ortg": 122.95,
    "drtg": 88.51,
    "netRtg": 34.44,
    "sos": 12.65,
    "srs": 25.14,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Arkansas",
    "seed": 4,
    "region": "West",
    "record": "25-8",
    "conf": "SEC",
    "srsRank": 17,
    "ortg": 127.93,
    "drtg": 98.34,
    "netRtg": 29.59,
    "sos": 19.56,
    "srs": 22.1,
    "pace": 72.4,
    "ftr": 0.367,
    "threePAr": 0.331,
    "tovPct": 10.6,
    "orbPct": 32.6
  },
  {
    "team": "Wisconsin",
    "seed": 5,
    "region": "West",
    "record": "24-10",
    "conf": "Big Ten",
    "srsRank": 25,
    "ortg": 125.86,
    "drtg": 98.59,
    "netRtg": 27.27,
    "sos": 14.66,
    "srs": 19.54,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "BYU",
    "seed": 6,
    "region": "West",
    "record": "25-8",
    "conf": "Big 12",
    "srsRank": 22,
    "ortg": 125.43,
    "drtg": 96.76,
    "netRtg": 28.67,
    "sos": 16.04,
    "srs": 21.05,
    "pace": 70.5,
    "ftr": 0.342,
    "threePAr": 0.398,
    "tovPct": 13.0,
    "orbPct": 34.6
  },
  {
    "team": "Miami",
    "seed": 7,
    "region": "West",
    "record": "25-8",
    "conf": "ACC",
    "srsRank": 30,
    "ortg": 121.37,
    "drtg": 97.33,
    "netRtg": 24.04,
    "sos": 10.1,
    "srs": 18.05,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Villanova",
    "seed": 8,
    "region": "West",
    "record": "24-8",
    "conf": "Big East",
    "srsRank": 40,
    "ortg": 120.41,
    "drtg": 97.32,
    "netRtg": 23.09,
    "sos": 6.62,
    "srs": 16.32,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Utah State",
    "seed": 9,
    "region": "West",
    "record": "28-6",
    "conf": "MWC",
    "srsRank": 33,
    "ortg": 122.63,
    "drtg": 98.16,
    "netRtg": 24.47,
    "sos": 10.4,
    "srs": 17.36,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Missouri",
    "seed": 10,
    "region": "West",
    "record": "20-12",
    "conf": "SEC",
    "srsRank": 54,
    "ortg": 118.29,
    "drtg": 101.28,
    "netRtg": 17.01,
    "sos": 7.04,
    "srs": 13.08,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Texas",
    "seed": 11,
    "region": "West",
    "record": "18-14",
    "conf": "SEC",
    "srsRank": 41,
    "ortg": 123.71,
    "drtg": 102.23,
    "netRtg": 21.48,
    "sos": 11.41,
    "srs": 16.18,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "High Point",
    "seed": 12,
    "region": "West",
    "record": "30-4",
    "conf": "Big South",
    "srsRank": 999,
    "ortg": 115.2,
    "drtg": 101.5,
    "netRtg": 13.7,
    "sos": -4.5,
    "srs": 8.4,
    "pace": 69.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Hawaii",
    "seed": 13,
    "region": "West",
    "record": "24-8",
    "conf": "Big West",
    "srsRank": 999,
    "ortg": 112.8,
    "drtg": 103.2,
    "netRtg": 9.6,
    "sos": -3.8,
    "srs": 6.2,
    "pace": 70.5,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Kennesaw State",
    "seed": 14,
    "region": "West",
    "record": "22-11",
    "conf": "ASUN",
    "srsRank": 999,
    "ortg": 107.0,
    "drtg": 102.8,
    "netRtg": 4.2,
    "sos": -5.0,
    "srs": 2.5,
    "pace": 68.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Queens",
    "seed": 15,
    "region": "West",
    "record": "20-13",
    "conf": "ASUN",
    "srsRank": 999,
    "ortg": 104.5,
    "drtg": 103.0,
    "netRtg": 1.5,
    "sos": -8.5,
    "srs": -0.2,
    "pace": 67.5,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "LIU",
    "seed": 16,
    "region": "West",
    "record": "22-11",
    "conf": "NEC",
    "srsRank": 999,
    "ortg": 106.0,
    "drtg": 104.5,
    "netRtg": 1.5,
    "sos": -10.0,
    "srs": -2.5,
    "pace": 69.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Michigan",
    "seed": 1,
    "region": "Midwest",
    "record": "31-2",
    "conf": "Big Ten",
    "srsRank": 1,
    "ortg": 128.57,
    "drtg": 83.99,
    "netRtg": 44.58,
    "sos": 19.69,
    "srs": 32.93,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Iowa State",
    "seed": 2,
    "region": "Midwest",
    "record": "27-7",
    "conf": "Big 12",
    "srsRank": 5,
    "ortg": 125.76,
    "drtg": 88.44,
    "netRtg": 37.32,
    "sos": 12.13,
    "srs": 27.15,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Virginia",
    "seed": 3,
    "region": "Midwest",
    "record": "29-5",
    "conf": "ACC",
    "srsRank": 19,
    "ortg": 123.2,
    "drtg": 92.72,
    "netRtg": 30.48,
    "sos": 9.95,
    "srs": 21.61,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Alabama",
    "seed": 4,
    "region": "Midwest",
    "record": "23-9",
    "conf": "SEC",
    "srsRank": 14,
    "ortg": 128.11,
    "drtg": 98.07,
    "netRtg": 30.04,
    "sos": 22.32,
    "srs": 22.7,
    "pace": 74.6,
    "ftr": 0.372,
    "threePAr": 0.537,
    "tovPct": 11.2,
    "orbPct": 31.8
  },
  {
    "team": "Texas Tech",
    "seed": 5,
    "region": "Midwest",
    "record": "22-10",
    "conf": "Big 12",
    "srsRank": 18,
    "ortg": 125.68,
    "drtg": 95.45,
    "netRtg": 30.23,
    "sos": 11.33,
    "srs": 21.94,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Tennessee",
    "seed": 6,
    "region": "Midwest",
    "record": "22-11",
    "conf": "SEC",
    "srsRank": 16,
    "ortg": 121.62,
    "drtg": 91.28,
    "netRtg": 30.34,
    "sos": 7.83,
    "srs": 22.11,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Kentucky",
    "seed": 7,
    "region": "Midwest",
    "record": "24-9",
    "conf": "SEC",
    "srsRank": 23,
    "ortg": 121.96,
    "drtg": 95.12,
    "netRtg": 26.84,
    "sos": 10.65,
    "srs": 19.82,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Georgia",
    "seed": 8,
    "region": "Midwest",
    "record": "22-10",
    "conf": "SEC",
    "srsRank": 24,
    "ortg": 123.98,
    "drtg": 99.08,
    "netRtg": 24.9,
    "sos": 18.2,
    "srs": 19.58,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "St. Louis",
    "seed": 9,
    "region": "Midwest",
    "record": "28-5",
    "conf": "A-10",
    "srsRank": 34,
    "ortg": 120.95,
    "drtg": 98.31,
    "netRtg": 22.64,
    "sos": 13.2,
    "srs": 17.29,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Santa Clara",
    "seed": 10,
    "region": "Midwest",
    "record": "26-8",
    "conf": "WCC",
    "srsRank": 42,
    "ortg": 122.51,
    "drtg": 100.78,
    "netRtg": 21.73,
    "sos": 12.31,
    "srs": 15.9,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "SMU",
    "seed": 11,
    "region": "Midwest",
    "record": "20-13",
    "conf": "ACC",
    "srsRank": 35,
    "ortg": 122.53,
    "drtg": 100.17,
    "netRtg": 22.36,
    "sos": 13.1,
    "srs": 17.29,
    "pace": null,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Akron",
    "seed": 12,
    "region": "Midwest",
    "record": "29-5",
    "conf": "MAC",
    "srsRank": 82,
    "ortg": 117.33,
    "drtg": 105.82,
    "netRtg": 11.51,
    "sos": 9.81,
    "srs": 9.05,
    "pace": 71.8,
    "ftr": 0.277,
    "threePAr": 0.451,
    "tovPct": 13.2,
    "orbPct": 34.0
  },
  {
    "team": "Hofstra",
    "seed": 13,
    "region": "Midwest",
    "record": "24-10",
    "conf": "CAA",
    "srsRank": 999,
    "ortg": 113.5,
    "drtg": 103.0,
    "netRtg": 10.5,
    "sos": -1.5,
    "srs": 8.4,
    "pace": 68.5,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Wright State",
    "seed": 14,
    "region": "Midwest",
    "record": "23-11",
    "conf": "Horizon",
    "srsRank": 999,
    "ortg": 109.2,
    "drtg": 103.5,
    "netRtg": 5.7,
    "sos": -6.0,
    "srs": 3.0,
    "pace": 68.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "Tennessee State",
    "seed": 15,
    "region": "Midwest",
    "record": "21-12",
    "conf": "OVC",
    "srsRank": 999,
    "ortg": 105.0,
    "drtg": 104.0,
    "netRtg": 1.0,
    "sos": -9.5,
    "srs": -1.5,
    "pace": 70.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "UMBC",
    "seed": 16,
    "region": "Midwest",
    "record": "24-8",
    "conf": "AE",
    "srsRank": 999,
    "ortg": 108.0,
    "drtg": 105.5,
    "netRtg": 2.5,
    "sos": -8.0,
    "srs": -5.9,
    "pace": 67.0,
    "ftr": null,
    "threePAr": null,
    "tovPct": null,
    "orbPct": null
  },
  {
    "team": "NC State",
    "seed": 11,
    "region": "West",
    "record": "20-13",
    "conf": "ACC",
    "srsRank": 31,
    "ortg": 125.32,
    "drtg": 100.72,
    "netRtg": 24.6,
    "sos": 14.37,
    "srs": 18.03,
    "pace": 69.0
  },
  {
    "team": "Miami (OH)",
    "seed": 11,
    "region": "Midwest",
    "record": "31-1",
    "conf": "MAC",
    "srsRank": 999,
    "ortg": 114.0,
    "drtg": 97.5,
    "netRtg": 16.5,
    "sos": -3.0,
    "srs": 10.5,
    "pace": 68.0
  },
  {
    "team": "Lehigh",
    "seed": 16,
    "region": "South",
    "record": "22-12",
    "conf": "Patriot",
    "srsRank": 999,
    "ortg": 105.5,
    "drtg": 103.0,
    "netRtg": 2.5,
    "sos": -8.0,
    "srs": -2.0,
    "pace": 67.5
  },
  {
    "team": "Howard",
    "seed": 16,
    "region": "Midwest",
    "record": "20-13",
    "conf": "MEAC",
    "srsRank": 999,
    "ortg": 102.0,
    "drtg": 106.5,
    "netRtg": -4.5,
    "sos": -11.0,
    "srs": -7.0,
    "pace": 69.5
  }
];

export const MADNESS_METRICS = [
  {
    "key": "ortg",
    "label": "Offensive Rating",
    "desc": "Points per 100 possessions",
    "higher": "better"
  },
  {
    "key": "drtg",
    "label": "Defensive Rating",
    "desc": "Opponent points per 100 possessions",
    "higher": "worse",
    "inverted": true
  },
  {
    "key": "netRtg",
    "label": "Net Rating",
    "desc": "Offensive - Defensive efficiency",
    "higher": "better"
  },
  {
    "key": "srs",
    "label": "Simple Rating System",
    "desc": "Margin of victory adjusted for schedule strength",
    "higher": "better"
  },
  {
    "key": "sos",
    "label": "Strength of Schedule",
    "desc": "Average opponent quality",
    "higher": "tougher"
  },
  {
    "key": "pace",
    "label": "Tempo",
    "desc": "Possessions per 40 minutes",
    "higher": "faster"
  },
  {
    "key": "ftr",
    "label": "Free Throw Rate",
    "desc": "FTA / FGA ratio",
    "higher": "more aggressive"
  },
  {
    "key": "threePAr",
    "label": "3-Point Rate",
    "desc": "3PA / FGA ratio",
    "higher": "more 3s"
  },
  {
    "key": "tovPct",
    "label": "Turnover %",
    "desc": "Turnovers per 100 plays",
    "higher": "worse",
    "inverted": true
  },
  {
    "key": "orbPct",
    "label": "Off. Rebound %",
    "desc": "Percentage of missed shots rebounded",
    "higher": "better"
  },
  {
    "key": "seed",
    "label": "Seed",
    "desc": "Tournament seed (1 = best)",
    "higher": "worse",
    "inverted": true
  }
];

export const REGION_COLORS = {East:'#dc2626',South:'#f59e0b',West:'#2563eb',Midwest:'#16a34a'};
