// NFL Rosters — auto-generated from Ourlads depth charts on 2026-03-05
// Run: claude agents/ourlads/AGENT.md to refresh

const NFL_ROSTERS = {
  "ARI": {
    "QB1": "Jacoby Brissett",
    "QB2": "Kedon Slovis",
    "RB1": "James Conner",
    "RB2": "Trey Benson",
    "WR1": "Marvin Harrison Jr.",
    "WR2": "Zay Jones",
    "WR3": "Michael Wilson",
    "TE1": "Trey McBride",
    "TE2": "Tip Reiman",
    "LT": "Paris Johnson Jr.",
    "LG": "Evan Brown",
    "C": "Hjalte Froholdt",
    "RG": "Isaiah Adams",
    "RT": "Jonah Williams",
    "DE1": "Calais Campbell",
    "DT1": "Dalvin Tomlinson",
    "DE2": "Walter Nolen III",
    "LB1": "Zaven Collins",
    "LB2": "Cody Simon",
    "LB3": "Mack Wilson Sr.",
    "LB4": "Josh Sweat",
    "CB1": "Will Johnson",
    "CB2": "Denzel Burke",
    "NB": "Garrett Williams",
    "SS": "Jalen Thompson",
    "FS": "Budda Baker",
    "K": "Chad Ryland"
  },
  "ATL": {
    "QB1": "Michael Penix Jr.",
    "QB2": "Easton Stick",
    "RB1": "Bijan Robinson",
    "RB2": "Tyler Allgeier",
    "WR1": "Casey Washington",
    "WR2": "David Sills V",
    "WR3": "Drake London",
    "TE1": "Kyle Pitts Sr.",
    "TE2": "Charlie Woerner",
    "LT": "Jake Matthews",
    "LG": "Matthew Bergeron",
    "C": "Ryan Neuzil",
    "RG": "Chris Lindstrom",
    "RT": "Kaleb McGary",
    "DE1": "David Onyemata",
    "DT1": "Ruke Orhorhoro",
    "DE2": "Brandon Dorlus",
    "LB1": "James Pearce Jr.",
    "LB2": "Kaden Elliss",
    "LB3": "Divine Deablo",
    "LB4": "Jalon Walker",
    "CB1": "Mike Hughes",
    "CB2": "A.J. Terrell Jr.",
    "NB": "Billy Bowman Jr.",
    "SS": "Jessie Bates III",
    "FS": "Xavier Watts",
    "K": "Zane Gonzalez"
  },
  "BAL": {
    "QB1": "Lamar Jackson",
    "QB2": "Tyler Huntley",
    "RB1": "Derrick Henry",
    "RB2": "Justice Hill",
    "WR1": "Rashod Bateman",
    "WR2": "Devontez Walker",
    "WR3": "Zay Flowers",
    "TE1": "Mark Andrews",
    "TE2": "Isaiah Likely",
    "LT": "Ronnie Stanley",
    "LG": "Andrew Vorhees",
    "C": "Tyler Linderbaum",
    "RG": "Daniel Faalele",
    "RT": "Roger Rosengarten",
    "DE1": "Nnamdi Madubuike",
    "DT1": "Travis Jones",
    "DE2": "Broderick Washington Jr.",
    "LB1": "Tavius Robinson",
    "LB2": "Teddye Buchanan",
    "LB3": "Roquan Smith",
    "LB4": "Mike Green",
    "CB1": "Marlon Humphrey",
    "CB2": "Nate Wiggins",
    "NB": "Kyle Hamilton",
    "SS": "Alohi Gilman",
    "FS": "Malaki Starks",
    "K": "Tyler Loop"
  },
  "BUF": {
    "QB1": "Josh Allen",
    "QB2": "Mitchell Trubisky",
    "RB1": "James Cook III",
    "RB2": "Ty Johnson",
    "WR1": "DJ Moore",
    "WR2": "Joshua Palmer",
    "WR3": "Khalil Shakir",
    "TE1": "Dawson Knox",
    "TE2": "Dalton Kincaid",
    "LT": "Dion Dawkins",
    "LG": "David Edwards",
    "C": "Connor McGovern",
    "RG": "O'Cyrus Torrence",
    "RT": "Spencer Brown",
    "DE1": "Ed Oliver",
    "DT1": "Deone Walker",
    "DE2": "T.J. Sanders",
    "LB1": "Joey Bosa",
    "LB2": "Matt Milano",
    "LB3": "Terrel Bernard",
    "LB4": "Greg Rousseau",
    "CB1": "Christian Benford",
    "CB2": "Tre'Davious White",
    "NB": "Taron Johnson",
    "SS": "Taylor Rapp",
    "FS": "Cole Bishop",
    "K": "Tyler Bass"
  },
  "CAR": {
    "QB1": "Bryce Young",
    "QB2": "Andy Dalton",
    "RB1": "Chuba Hubbard",
    "RB2": "Rico Dowdle",
    "WR1": "Tetairoa McMillan",
    "WR2": "Xavier Legette",
    "WR3": "Jalen Coker",
    "TE1": "Tommy Tremble",
    "TE2": "Ja'Tavion Sanders",
    "LT": "Ikem Ekwonu",
    "LG": "Damien Lewis",
    "C": "Cade Mays",
    "RG": "Robert Hunt",
    "RT": "Taylor Moton",
    "DE1": "Derrick Brown",
    "DT1": "A'Shawn Robinson",
    "DE2": "Tershawn Wharton",
    "LB1": "Nic Scourton",
    "LB2": "Trevin Wallace",
    "LB3": "Christian Rozeboom",
    "LB4": "D.J. Wonnum",
    "CB1": "Mike Jackson",
    "CB2": "Jaycee Horn",
    "NB": "Chau Smith-Wade",
    "SS": "Tre'von Moehrig",
    "FS": "Nick Scott",
    "K": "Ryan Fitzgerald"
  },
  "CHI": {
    "QB1": "Caleb Williams",
    "QB2": "Tyson Bagent",
    "RB1": "D'Andre Swift",
    "RB2": "Kyle Monangai",
    "WR1": "Rome Odunze",
    "WR2": "Luther Burden III",
    "WR3": "Olamide Zaccheaus",
    "TE1": "Colston Loveland",
    "TE2": "Cole Kmet",
    "LT": "Theo Benedet",
    "LG": "Joe Thuney",
    "C": "Ryan Bates",
    "RG": "Jonah Jackson",
    "RT": "Darnell Wright",
    "DE1": "Montez Sweat",
    "DT1": "Gervon Dexter Sr.",
    "DT2": "Grady Jarrett",
    "DE2": "Dayo Odeyingbo",
    "LB1": "T.J. Edwards",
    "LB2": "Tremaine Edmunds",
    "CB1": "Nahshon Wright",
    "CB2": "Jaylon Johnson",
    "NB": "Kyler Gordon",
    "SS": "Jaquan Brisker",
    "FS": "Kevin Byard III",
    "K": "Cairo Santos"
  },
  "CIN": {
    "QB1": "Joe Burrow",
    "QB2": "Joe Flacco",
    "RB1": "Chase Brown",
    "RB2": "Samaje Perine",
    "WR1": "Ja'Marr Chase",
    "WR2": "Tee Higgins",
    "WR3": "Andrei Iosivas",
    "TE1": "Mike Gesicki",
    "TE2": "Drew Sample",
    "LT": "Orlando Brown Jr.",
    "LG": "Dylan Fairchild",
    "C": "Ted Karras",
    "RG": "Dalton Risner",
    "RT": "Amarius Mims",
    "DE1": "Joseph Ossai",
    "DT1": "T.J. Slaton Jr.",
    "DT2": "B.J. Hill",
    "DE2": "Trey Hendrickson",
    "LB1": "Demetrius Knight Jr.",
    "LB2": "Barrett Carter",
    "CB1": "Dax Hill",
    "CB2": "DJ Turner II",
    "NB": "Jalen Davis",
    "SS": "Jordan Battle",
    "FS": "Geno Stone",
    "K": "Evan McPherson"
  },
  "CLE": {
    "QB1": "Shedeur Sanders",
    "QB2": "Dillon Gabriel",
    "RB1": "Quinshon Judkins",
    "RB2": "Dylan Sampson",
    "WR1": "Jerry Jeudy",
    "WR2": "Cedric Tillman",
    "WR3": "Isaiah Bond",
    "TE1": "Harold Fannin Jr.",
    "TE2": "David Njoku",
    "LT": "Dawand Jones",
    "LG": "Joel Bitonio",
    "C": "Ethan Pocic",
    "RG": "Wyatt Teller",
    "RT": "Tytus Howard",
    "DE1": "Alex Wright",
    "DT1": "Maliek Collins",
    "DT2": "Mason Graham",
    "DE2": "Myles Garrett",
    "LB1": "Devin Bush",
    "LB2": "Carson Schwesinger",
    "CB1": "Denzel Ward",
    "CB2": "Tyson Campbell",
    "NB": "Myles Harden",
    "SS": "Grant Delpit",
    "FS": "Ronnie Hickman",
    "K": "Andre Szmyt"
  },
  "DAL": {
    "QB1": "Dak Prescott",
    "QB2": "Joe Milton III",
    "RB1": "Javonte Williams",
    "RB2": "Malik Davis",
    "WR1": "George Pickens",
    "WR2": "CeeDee Lamb",
    "WR3": "Ryan Flournoy",
    "TE1": "Jake Ferguson",
    "TE2": "Luke Schoonmaker",
    "LT": "Tyler Guyton",
    "LG": "Tyler Smith",
    "C": "Cooper Beebe",
    "RG": "Tyler Booker",
    "RT": "Terence Steele",
    "DE1": "Osa Odighizuwa",
    "DT1": "Kenny Clark",
    "DE2": "Quinnen Williams",
    "LB1": "Jadeveon Clowney",
    "LB2": "DeMarvion Overshown",
    "LB3": "Kenneth Murray Jr.",
    "LB4": "Donovan Ezeiruaku",
    "CB1": "DaRon Bland",
    "CB2": "Shavon Revel Jr.",
    "NB": "Reddy Steward",
    "SS": "Donovan Wilson",
    "FS": "Malik Hooker",
    "K": "Brandon Aubrey"
  },
  "DEN": {
    "QB1": "Bo Nix",
    "QB2": "Jarrett Stidham",
    "RB1": "J.K. Dobbins",
    "RB2": "RJ Harvey",
    "WR1": "Courtland Sutton",
    "WR2": "Troy Franklin",
    "WR3": "Pat Bryant",
    "TE1": "Adam Trautman",
    "TE2": "Evan Engram",
    "LT": "Garett Bolles",
    "LG": "Ben Powers",
    "C": "Luke Wattenberg",
    "RG": "Quinn Meinerz",
    "RT": "Mike McGlinchey",
    "DE1": "Zach Allen",
    "DT1": "Malcolm Roach",
    "DE2": "John Franklin-Myers",
    "LB1": "Jonathon Cooper",
    "LB2": "Dre Greenlaw",
    "LB3": "Alex Singleton",
    "LB4": "Nik Bonitto",
    "CB1": "Riley Moss",
    "CB2": "Pat Surtain II",
    "NB": "Ja'Quan McMillian",
    "SS": "Talanoa Hufanga",
    "FS": "Brandon Jones",
    "K": "Wil Lutz"
  },
  "DET": {
    "QB1": "Jared Goff",
    "QB2": "Kyle Allen",
    "RB1": "Jahmyr Gibbs",
    "RB2": "Jacob Saylors",
    "WR1": "Isaac TeSlaa",
    "WR2": "Jameson Williams",
    "WR3": "Amon-Ra St. Brown",
    "TE1": "Sam LaPorta",
    "TE2": "Brock Wright",
    "LT": "Taylor Decker",
    "LG": "Christian Mahogany",
    "C": "Juice Scruggs",
    "RG": "Tate Ratledge",
    "RT": "Penei Sewell",
    "DE1": "Aidan Hutchinson",
    "DT1": "DJ Reader",
    "DT2": "Alim McNeill",
    "DE2": "Marcus Davenport",
    "LB1": "Alex Anzalone",
    "LB2": "Jack Campbell",
    "LB3": "Derrick Barnes",
    "CB1": "Terrion Arnold",
    "CB2": "D.J. Reed",
    "NB": "Amik Robertson",
    "SS": "Brian Branch",
    "FS": "Kerby Joseph",
    "K": "Jake Bates"
  },
  "GB": {
    "QB1": "Jordan Love",
    "QB2": "Malik Willis",
    "RB1": "Josh Jacobs",
    "RB2": "Emanuel Wilson",
    "WR1": "Christian Watson",
    "WR2": "Romeo Doubs",
    "WR3": "Jayden Reed",
    "TE1": "Tucker Kraft",
    "TE2": "John FitzPatrick",
    "LT": "Rasheed Walker",
    "LG": "Aaron Banks",
    "C": "Elgton Jenkins",
    "RG": "Sean Rhyan",
    "RT": "Zach Tom",
    "DE1": "Rashan Gary",
    "DT1": "Karl Brooks",
    "DT2": "Devonte Wyatt",
    "DE2": "Micah Parsons",
    "LB1": "Edgerrin Cooper",
    "LB2": "Quay Walker",
    "CB1": "Keisean Nixon",
    "CB2": "Carrington Valentine",
    "NB": "Javon Bullard",
    "SS": "Xavier McKinney",
    "FS": "Evan Williams",
    "K": "Brandon McManus"
  },
  "HOU": {
    "QB1": "C.J. Stroud",
    "QB2": "Davis Mills",
    "RB1": "David Montgomery",
    "RB2": "Woody Marks",
    "WR1": "Nico Collins",
    "WR2": "Jayden Higgins",
    "WR3": "Christian Kirk",
    "TE1": "Dalton Schultz",
    "TE2": "Cade Stover",
    "LT": "Aireontae Ersery",
    "LG": "Jarrett Patterson",
    "C": "Jake Andrews",
    "RG": "Ed Ingram",
    "RT": "Trent Brown",
    "DE1": "Will Anderson Jr.",
    "DT1": "Sheldon Rankins",
    "DT2": "Tim Settle Jr.",
    "DE2": "Danielle Hunter",
    "LB1": "Henry To'oTo'o",
    "LB2": "Azeez Al-Shaair",
    "CB1": "Derek Stingley Jr.",
    "CB2": "Kamari Lassiter",
    "NB": "Jalen Pitre",
    "SS": "M.J. Stewart",
    "FS": "Calen Bullock",
    "K": "Ka'imi Fairbairn"
  },
  "IND": {
    "QB1": "Daniel Jones",
    "QB2": "Anthony Richardson Sr.",
    "RB1": "Jonathan Taylor",
    "RB2": "Ameer Abdullah",
    "WR1": "Michael Pittman Jr.",
    "WR2": "Alec Pierce",
    "WR3": "Josh Downs",
    "TE1": "Tyler Warren",
    "TE2": "Mo Alie-Cox",
    "LT": "Bernhard Raimann",
    "LG": "Quenton Nelson",
    "C": "Tanor Bortolini",
    "RG": "Matt Goncalves",
    "RT": "Braden Smith",
    "DE1": "Kwity Paye",
    "DT1": "Grover Stewart",
    "DT2": "DeForest Buckner",
    "DE2": "Laiatu Latu",
    "LB1": "Germaine Pratt",
    "LB2": "Zaire Franklin",
    "CB1": "Charvarius Ward",
    "CB2": "Sauce Gardner",
    "NB": "Kenny Moore II",
    "SS": "Nick Cross",
    "FS": "Cam Bynum",
    "K": "Spencer Shrader"
  },
  "JAX": {
    "QB1": "Trevor Lawrence",
    "QB2": "Nick Mullens",
    "RB1": "Travis Etienne Jr.",
    "RB2": "Bhayshul Tuten",
    "WR1": "Brian Thomas Jr.",
    "WR2": "Jakobi Meyers",
    "WR3": "Parker Washington",
    "TE1": "Brenton Strange",
    "TE2": "Quintin Morris",
    "LT": "Cole Van Lanen",
    "LG": "Ezra Cleveland",
    "C": "Robert Hainsey",
    "RG": "Patrick Mekari",
    "RT": "Anton Harrison",
    "DE1": "Travon Walker",
    "DT1": "DaVon Hamilton",
    "DT2": "Arik Armstead",
    "DE2": "Josh Hines-Allen",
    "LB1": "Foyesade Oluokun",
    "LB2": "Devin Lloyd",
    "CB1": "Montaric Brown",
    "CB2": "Greg Newsome II",
    "NB": "Jourdan Lewis",
    "SS": "Antonio Johnson",
    "FS": "Eric Murray",
    "K": "Cam Little"
  },
  "KC": {
    "QB1": "Patrick Mahomes",
    "QB2": "Gardner Minshew",
    "RB1": "Isiah Pacheco",
    "RB2": "Kareem Hunt",
    "WR1": "Hollywood Brown",
    "WR2": "Xavier Worthy",
    "WR3": "Rashee Rice",
    "TE1": "Travis Kelce",
    "TE2": "Noah Gray",
    "LT": "Josh Simmons",
    "LG": "Kingsley Suamataia",
    "C": "Creed Humphrey",
    "RG": "Trey Smith",
    "RT": "Jaylon Moore",
    "DE1": "George Karlaftis",
    "DT1": "Chris Jones",
    "DT2": "Jerry Tillery",
    "DE2": "Ashton Gillotte",
    "LB1": "Drue Tranquill",
    "LB2": "Nick Bolton",
    "LB3": "Leo Chenal",
    "CB1": "Jaylen Watson",
    "CB2": "Nohl Williams",
    "NB": "Chris Roland-Wallace",
    "SS": "Chamarri Conner",
    "FS": "Bryan Cook",
    "K": "Harrison Butker"
  },
  "LV": {
    "QB1": "Geno Smith",
    "QB2": "Kenny Pickett",
    "RB1": "Ashton Jeanty",
    "RB2": "Raheem Mostert",
    "WR1": "Jack Bech",
    "WR2": "Tre Tucker",
    "WR3": "Tyler Lockett",
    "TE1": "Brock Bowers",
    "TE2": "Michael Mayer",
    "LT": "Kolton Miller",
    "LG": "Dylan Parham",
    "C": "Jordan Meredith",
    "RG": "Jackson Powers-Johnson",
    "RT": "DJ Glaze",
    "DE1": "Tyree Wilson",
    "DT1": "Adam Butler",
    "DE2": "Jonah Laulu",
    "LB1": "Maxx Crosby",
    "LB2": "Elandon Roberts",
    "LB3": "Devin White",
    "LB4": "Malcolm Koonce",
    "CB1": "Eric Stokes",
    "CB2": "Kyu Blu Kelly",
    "NB": "Jeremy Chinn",
    "SS": "Isaiah Pola-Mao",
    "FS": "Lonnie Johnson Jr.",
    "K": "Daniel Carlson"
  },
  "LAC": {
    "QB1": "Justin Herbert",
    "QB2": "Trey Lance",
    "RB1": "Omarion Hampton",
    "RB2": "Najee Harris",
    "WR1": "Quentin Johnston",
    "WR2": "Keenan Allen",
    "WR3": "Ladd McConkey",
    "TE1": "Oronde Gadsden",
    "TE2": "Tucker Fisk",
    "LT": "Rashawn Slater",
    "LG": "Zion Johnson",
    "C": "Andre James",
    "RG": "Jamaree Salyer",
    "RT": "Joe Alt",
    "DE1": "Da'Shawn Hand",
    "DT1": "Jamaree Caldwell",
    "DE2": "Teair Tart",
    "LB1": "Tuli Tuipulotu",
    "LB2": "Denzel Perryman",
    "LB3": "Daiyan Henley",
    "LB4": "Khalil Mack",
    "CB1": "Tarheeb Still",
    "CB2": "Cam Hart",
    "NB": "Derwin James Jr.",
    "SS": "Elijah Molden",
    "FS": "Tony Jefferson",
    "K": "Cameron Dicker"
  },
  "LAR": {
    "QB1": "Matthew Stafford",
    "QB2": "Jimmy Garoppolo",
    "RB1": "Kyren Williams",
    "RB2": "Blake Corum",
    "WR1": "Davante Adams",
    "WR2": "Puka Nacua",
    "WR3": "Jordan Whittington",
    "TE1": "Colby Parkinson",
    "TE2": "Terrance Ferguson",
    "LT": "Alaric Jackson",
    "LG": "Steve Avila",
    "C": "Coleman Shelton",
    "RG": "Kevin Dotson",
    "RT": "Warren McClendon Jr.",
    "DE1": "Braden Fiske",
    "DT1": "Poona Ford",
    "DE2": "Kobie Turner",
    "LB1": "Byron Young",
    "LB2": "Nate Landman",
    "LB3": "Omar Speights",
    "LB4": "Jared Verse",
    "CB1": "Cobie Durant",
    "CB2": "Trent McDuffie",
    "NB": "Quentin Lake",
    "SS": "Kam Curl",
    "FS": "Kamren Kinchens",
    "K": "Harrison Mevis"
  },
  "MIA": {
    "QB1": "Quinn Ewers",
    "QB2": "Zach Wilson",
    "RB1": "De'Von Achane",
    "RB2": "Jaylen Wright",
    "WR1": "Jaylen Waddle",
    "WR2": "Cedrick Wilson Jr.",
    "WR3": "Malik Washington",
    "TE1": "Darren Waller",
    "TE2": "Julian Hill",
    "LT": "Patrick Paul",
    "LG": "Jonah Savaiinaea",
    "C": "Aaron Brewer",
    "RG": "Cole Strange",
    "RT": "Austin Jackson",
    "DE1": "Kenneth Grant",
    "DT1": "Jordan Phillips",
    "DE2": "Zach Sieler",
    "LB1": "Chop Robinson",
    "LB2": "Jordyn Brooks",
    "LB3": "Tyrel Dodson",
    "LB4": "Quinton Bell",
    "CB1": "Rasul Douglas",
    "CB2": "Storm Duck",
    "NB": "Kader Kohou",
    "SS": "Ashtyn Davis",
    "FS": "Minkah Fitzpatrick",
    "K": "Jason Sanders"
  },
  "MIN": {
    "QB1": "J.J. McCarthy",
    "QB2": "Carson Wentz",
    "RB1": "Jordan Mason",
    "RB2": "Ty Chandler",
    "WR1": "Justin Jefferson",
    "WR2": "Jordan Addison",
    "WR3": "Jalen Nailor",
    "TE1": "T.J. Hockenson",
    "TE2": "Josh Oliver",
    "LT": "Christian Darrisaw",
    "LG": "Donovan Jackson",
    "C": "Ryan Kelly",
    "RG": "Will Fries",
    "RT": "Brian O'Neill",
    "DE1": "Tyrion Ingram-Dawkins",
    "DT1": "Levi Drake Rodriguez",
    "DE2": "Jalen Redmond",
    "LB1": "Jonathan Greenard",
    "LB2": "Eric Wilson",
    "LB3": "Blake Cashman",
    "LB4": "Andrew Van Ginkel",
    "CB1": "Isaiah Rodgers",
    "CB2": "Byron Murphy Jr.",
    "SS": "Joshua Metellus",
    "FS": "Harrison Smith",
    "K": "Will Reichard"
  },
  "NE": {
    "QB1": "Drake Maye",
    "QB2": "Joshua Dobbs",
    "RB1": "Rhamondre Stevenson",
    "RB2": "TreVeyon Henderson",
    "WR1": "Kayshon Boutte",
    "WR2": "Mack Hollins",
    "WR3": "DeMario Douglas",
    "TE1": "Hunter Henry",
    "TE2": "Austin Hooper",
    "LT": "Will Campbell",
    "LG": "Jared Wilson",
    "C": "Garrett Bradbury",
    "RG": "Mike Onwenu",
    "RT": "Morgan Moses",
    "DE1": "Milton Williams",
    "DT1": "Cory Durden",
    "DE2": "Christian Barmore",
    "LB1": "Anfernee Jennings",
    "LB2": "Robert Spillane",
    "LB3": "Christian Elliss",
    "LB4": "K'Lavon Chaisson",
    "CB1": "Carlton Davis III",
    "CB2": "Christian Gonzalez",
    "NB": "Marcus Jones",
    "SS": "Craig Woodson",
    "FS": "Jaylinn Hawkins",
    "K": "Andy Borregales"
  },
  "NO": {
    "QB1": "Tyler Shough",
    "QB2": "Spencer Rattler",
    "RB1": "Alvin Kamara",
    "RB2": "Kendre Miller",
    "WR1": "Mason Tipton",
    "WR2": "Chris Olave",
    "WR3": "Devaughn Vele",
    "TE1": "Juwan Johnson",
    "TE2": "Foster Moreau",
    "LT": "Kelvin Banks Jr.",
    "LG": "Dillon Radunz",
    "C": "Erik McCoy",
    "RG": "Cesar Ruiz",
    "RT": "Taliese Fuaga",
    "DE1": "Bryan Bresee",
    "DT1": "Nathan Shepherd",
    "DE2": "Jonah Williams",
    "LB1": "Cameron Jordan",
    "LB2": "Pete Werner",
    "LB3": "Demario Davis",
    "LB4": "Chase Young",
    "CB1": "Quincy Riley",
    "CB2": "Kool-Aid McKinstry",
    "NB": "Alontae Taylor",
    "SS": "Justin Reid",
    "FS": "Jonas Sanker",
    "K": "Charlie Smyth"
  },
  "NYG": {
    "QB1": "Jaxson Dart",
    "QB2": "Jameis Winston",
    "RB1": "Cam Skattebo",
    "RB2": "Tyrone Tracy Jr.",
    "WR1": "Malik Nabers",
    "WR2": "Darius Slayton",
    "WR3": "Wan'Dale Robinson",
    "TE1": "Theo Johnson",
    "TE2": "Daniel Bellinger",
    "LT": "Andrew Thomas",
    "LG": "Jon Runyan",
    "C": "John Michael Schmitz Jr.",
    "RG": "Greg Van Roten",
    "RT": "Jermaine Eluemunor",
    "DE1": "Brian Burns",
    "DT1": "Dexter Lawrence II",
    "DT2": "Roy Robertson-Harris",
    "DE2": "Abdul Carter",
    "LB1": "Darius Muasau",
    "LB2": "Micah McFadden",
    "CB1": "Paulson Adebo",
    "CB2": "Cor'Dale Flott",
    "NB": "Dru Phillips",
    "SS": "Tyler Nubin",
    "FS": "Jevon Holland",
    "K": "Graham Gano"
  },
  "NYJ": {
    "QB1": "Justin Fields",
    "QB2": "Brady Cook",
    "RB1": "Breece Hall",
    "RB2": "Braelon Allen",
    "WR1": "Adonai Mitchell",
    "WR2": "Garrett Wilson",
    "WR3": "John Metchie III",
    "TE1": "Mason Taylor",
    "TE2": "Jeremy Ruckert",
    "LT": "Olu Fashanu",
    "LG": "John Simpson",
    "C": "Joe Tippmann",
    "RG": "Alijah Vera-Tucker",
    "RT": "Armand Membou",
    "DE1": "Jowon Briggs",
    "DT1": "T'Vondre Sweat",
    "DE2": "Harrison Phillips",
    "LB1": "Will McDonald IV",
    "LB2": "Quincy Williams",
    "LB3": "Jamien Sherwood",
    "LB4": "Micheal Clemons",
    "CB1": "Azareye'h Thomas",
    "CB2": "Brandon Stephens",
    "NB": "Jarvis Brownlee Jr.",
    "SS": "Malachi Moore",
    "FS": "Andre Cisco",
    "K": "Nick Folk"
  },
  "PHI": {
    "QB1": "Jalen Hurts",
    "QB2": "Tanner McKee",
    "RB1": "Saquon Barkley",
    "RB2": "Tank Bigsby",
    "WR1": "A.J. Brown",
    "WR2": "Jahan Dotson",
    "WR3": "DeVonta Smith",
    "TE1": "Dallas Goedert",
    "TE2": "Grant Calcaterra",
    "LT": "Jordan Mailata",
    "LG": "Landon Dickerson",
    "C": "Cam Jurgens",
    "RG": "Tyler Steen",
    "RT": "Lane Johnson",
    "DE1": "Moro Ojomo",
    "DT1": "Jordan Davis",
    "DE2": "Jalen Carter",
    "LB1": "Jaelan Phillips",
    "LB2": "Zack Baun",
    "LB3": "Nakobe Dean",
    "LB4": "Nolan Smith Jr.",
    "CB1": "Quinyon Mitchell",
    "CB2": "Adoree' Jackson",
    "NB": "Cooper DeJean",
    "SS": "Andrew Mukuba",
    "FS": "Reed Blankenship",
    "K": "Jake Elliott"
  },
  "PIT": {
    "QB1": "Aaron Rodgers",
    "QB2": "Mason Rudolph",
    "RB1": "Kenneth Gainwell",
    "RB2": "Jaylen Warren",
    "WR1": "DK Metcalf",
    "WR2": "Marquez Valdes-Scantling",
    "WR3": "Calvin Austin III",
    "TE1": "Darnell Washington",
    "TE2": "Pat Freiermuth",
    "LT": "Broderick Jones",
    "LG": "Isaac Seumalo",
    "C": "Zach Frazier",
    "RG": "Mason McCormick",
    "RT": "Troy Fautanu",
    "DE1": "Derrick Harmon",
    "DT1": "Keeanu Benton",
    "DE2": "Cameron Heyward",
    "LB1": "T.J. Watt",
    "LB2": "Patrick Queen",
    "LB3": "Payton Wilson",
    "LB4": "Alex Highsmith",
    "CB1": "James Pierre",
    "CB2": "Joey Porter Jr.",
    "NB": "Jalen Ramsey",
    "SS": "DeShon Elliott",
    "FS": "Kyle Dugger",
    "K": "Chris Boswell"
  },
  "SF": {
    "QB1": "Brock Purdy",
    "QB2": "Mac Jones",
    "RB1": "Christian McCaffrey",
    "RB2": "Brian Robinson Jr.",
    "WR1": "Ricky Pearsall",
    "WR2": "Jauan Jennings",
    "WR3": "DeMarcus Robinson",
    "TE1": "George Kittle",
    "TE2": "Luke Farrell",
    "LT": "Trent Williams",
    "LG": "Spencer Burford",
    "C": "Jake Brendel",
    "RG": "Dominick Puni",
    "RT": "Colton McKivitz",
    "DE1": "Mykel Williams",
    "DT1": "Jordan Elliott",
    "DT2": "Kalia Davis",
    "DE2": "Nick Bosa",
    "LB1": "Dee Winters",
    "LB2": "Fred Warner",
    "CB1": "Renardo Green",
    "CB2": "Deommodore Lenoir",
    "NB": "Upton Stout",
    "SS": "Ji'Ayir Brown",
    "FS": "Malik Mustapha",
    "K": "Eddy Pineiro"
  },
  "SEA": {
    "QB1": "Sam Darnold",
    "QB2": "Drew Lock",
    "RB1": "Kenneth Walker III",
    "RB2": "Zach Charbonnet",
    "WR1": "Jaxon Smith-Njigba",
    "WR2": "Rashid Shaheed",
    "WR3": "Cooper Kupp",
    "TE1": "AJ Barner",
    "TE2": "Eric Saubert",
    "LT": "Charles Cross",
    "LG": "Grey Zabel",
    "C": "Jalen Sundell",
    "RG": "Anthony Bradford",
    "RT": "Abraham Lucas",
    "DE1": "Leonard Williams",
    "DT1": "Byron Murphy II",
    "DE2": "Jarran Reed",
    "LB1": "DeMarcus Lawrence",
    "LB2": "Drake Thomas",
    "LB3": "Ernest Jones IV",
    "LB4": "Uchenna Nwosu",
    "CB1": "Devon Witherspoon",
    "CB2": "Josh Jobe",
    "NB": "Nick Emmanwori",
    "SS": "Julian Love",
    "FS": "Coby Bryant",
    "K": "Jason Myers"
  },
  "TB": {
    "QB1": "Baker Mayfield",
    "QB2": "Teddy Bridgewater",
    "RB1": "Bucky Irving",
    "RB2": "Rachaad White",
    "WR1": "Mike Evans",
    "WR2": "Emeka Egbuka",
    "WR3": "Chris Godwin Jr.",
    "TE1": "Cade Otton",
    "TE2": "Payne Durham",
    "LT": "Tristan Wirfs",
    "LG": "Ben Bredeson",
    "C": "Graham Barton",
    "RG": "Cody Mauch",
    "RT": "Luke Goedeke",
    "DE1": "Logan Hall",
    "DT1": "Vita Vea",
    "DE2": "Calijah Kancey",
    "LB1": "Haason Reddick",
    "LB2": "Lavonte David",
    "LB3": "SirVocea Dennis",
    "LB4": "Yaya Diaby",
    "CB1": "Zyon McCollum",
    "CB2": "Jamel Dean",
    "NB": "Jacob Parrish",
    "SS": "Tykee Smith",
    "FS": "Antoine Winfield Jr.",
    "K": "Chase McLaughlin"
  },
  "TEN": {
    "QB1": "Cam Ward",
    "QB2": "Will Levis",
    "RB1": "Tony Pollard",
    "RB2": "Tyjae Spears",
    "WR1": "Elic Ayomanor",
    "WR2": "Calvin Ridley",
    "WR3": "Chimere Dike",
    "TE1": "Chig Okonkwo",
    "TE2": "Gunnar Helm",
    "LT": "Dan Moore Jr.",
    "LG": "Peter Skoronski",
    "C": "Corey Levin",
    "RG": "Kevin Zeitler",
    "RT": "JC Latham",
    "DE1": "Jermaine Johnson",
    "DT1": "Jeffery Simmons",
    "DT2": "Sebastian Joseph-Day",
    "DE2": "Oluwafemi Oladejo",
    "LB1": "Cedric Gray",
    "LB2": "Cody Barton",
    "CB1": "Darrell Baker Jr.",
    "CB2": "L'Jarius Sneed",
    "NB": "Marcus Harris",
    "SS": "Amani Hooker",
    "FS": "Kevin Winston Jr.",
    "K": "Joey Slye"
  },
  "WAS": {
    "QB1": "Jayden Daniels",
    "QB2": "Marcus Mariota",
    "RB1": "Austin Ekeler",
    "RB2": "Chris Rodriguez Jr.",
    "WR1": "Terry McLaurin",
    "WR2": "Luke McCaffrey",
    "WR3": "Deebo Samuel",
    "TE1": "Zach Ertz",
    "TE2": "John Bates",
    "LT": "Laremy Tunsil",
    "LG": "Chris Paul",
    "C": "Nick Allegretti",
    "RG": "Sam Cosmi",
    "RT": "Josh Conerly Jr.",
    "DE1": "Deatrich Wise Jr.",
    "DT1": "Daron Payne",
    "DT2": "Javon Kinlaw",
    "DE2": "Dorance Armstrong",
    "LB1": "Frankie Luvu",
    "LB2": "Bobby Wagner",
    "CB1": "Trey Amos",
    "CB2": "Mike Sainristil",
    "NB": "Noah Igbinoghene",
    "SS": "Will Harris",
    "FS": "Jeremy Reaves",
    "K": "Jake Moody"
  }
};

export default NFL_ROSTERS;
