// NFL Rosters — auto-generated from ESPN depth charts on 2026-02-19
// Run: node updateRosters.js to refresh

const NFL_ROSTERS = {
  "ARI": {
    "DE1": "Josh Sweat",
    "DE2": "Jordan Burch",
    "DT1": "Calais Campbell",
    "DT2": "PJ Mustipher",
    "LB1": "Akeem Davis-Gaither",
    "LB2": "Owen Pappoe",
    "LB3": "Channing Tindall",
    "CB1": "Will Johnson",
    "CB2": "Sean Murphy-Bunting",
    "SS1": "Jalen Thompson",
    "FS1": "Budda Baker",
    "K1": "Chad Ryland",
    "WR1": "Marvin Harrison Jr.",
    "WR2": "Michael Wilson",
    "WR3": "Greg Dortch",
    "LT1": "Paris Johnson Jr.",
    "LG1": "Evan Brown",
    "C1": "Hjalte Froholdt",
    "RG1": "Will Hernandez",
    "RT1": "Jonah Williams",
    "QB1": "Jacoby Brissett",
    "QB2": "Kyler Murray",
    "TE1": "Trey McBride",
    "TE2": "Tip Reiman",
    "RB1": "James Conner",
    "RB2": "Trey Benson"
  },
  "ATL": {
    "DE1": "Zach Harrison",
    "DE2": "LaCale London",
    "DT1": "Ruke Orhorhoro",
    "DT2": "Kentavius Street",
    "LB1": "Jalon Walker",
    "LB2": "Leonard Floyd",
    "LB3": "Khalid Kareem",
    "CB1": "A.J. Terrell Jr.",
    "CB2": "Clark Phillips III",
    "SS1": "Jessie Bates III",
    "FS1": "Xavier Watts",
    "K1": "Zane Gonzalez",
    "WR1": "Drake London",
    "WR2": "Darnell Mooney",
    "WR3": "David Sills V",
    "LT1": "Jake Matthews",
    "LG1": "Matthew Bergeron",
    "C1": "Ryan Neuzil",
    "RG1": "Chris Lindstrom",
    "RT1": "Kaleb McGary",
    "QB1": "Michael Penix Jr.",
    "QB2": "Kirk Cousins",
    "TE1": "Kyle Pitts Sr.",
    "TE2": "Charlie Woerner",
    "RB1": "Bijan Robinson",
    "RB2": "Tyler Allgeier"
  },
  "BAL": {
    "DE1": "Travis Jones",
    "DE2": "Broderick Washington Jr.",
    "DT1": "John Jenkins",
    "LB1": "Kyle Van Noy",
    "LB2": "Mike Green",
    "LB3": "Tavius Robinson",
    "CB1": "Nate Wiggins",
    "CB2": "Bilhal Kone",
    "SS1": "Kyle Hamilton",
    "FS1": "Alohi Gilman",
    "K1": "Tyler Loop",
    "WR1": "Zay Flowers",
    "WR2": "Rashod Bateman",
    "WR3": "DeAndre Hopkins",
    "LT1": "Ronnie Stanley",
    "LG1": "Andrew Vorhees",
    "C1": "Tyler Linderbaum",
    "RG1": "Daniel Faalele",
    "RT1": "Roger Rosengarten",
    "QB1": "Lamar Jackson",
    "QB2": "Tyler Huntley",
    "TE1": "Mark Andrews",
    "TE2": "Isaiah Likely",
    "RB1": "Derrick Henry",
    "RB2": "Justice Hill"
  },
  "BUF": {
    "DE1": "Greg Rousseau",
    "DE2": "AJ Epenesa",
    "DT1": "Ed Oliver",
    "DT2": "Deone Walker",
    "LB1": "Matt Milano",
    "LB2": "Joe Andreessen",
    "LB3": "Terrel Bernard",
    "CB1": "Tre'Davious White",
    "CB2": "Dane Jackson",
    "SS1": "Taylor Rapp",
    "FS1": "Cole Bishop",
    "K1": "Tyler Bass",
    "WR1": "Khalil Shakir",
    "WR2": "Joshua Palmer",
    "WR3": "Keon Coleman",
    "LT1": "Dion Dawkins",
    "LG1": "David Edwards",
    "C1": "Connor McGovern",
    "RG1": "O'Cyrus Torrence",
    "RT1": "Spencer Brown",
    "QB1": "Josh Allen",
    "QB2": "Mitchell Trubisky",
    "TE1": "Dalton Kincaid",
    "TE2": "Dawson Knox",
    "RB1": "James Cook III",
    "RB2": "Ty Johnson"
  },
  "CAR": {
    "DE1": "Tershawn Wharton",
    "DE2": "Bobby Brown III",
    "DT1": "A'Shawn Robinson",
    "DT2": "Cam Jackson",
    "LB1": "Nic Scourton",
    "LB2": "Patrick Jones II",
    "LB3": "Trevis Gipson",
    "CB1": "Mike Jackson",
    "CB2": "Damarri Mathis",
    "SS1": "Tre'von Moehrig",
    "FS1": "Nick Scott",
    "K1": "Ryan Fitzgerald",
    "WR1": "Tetairoa McMillan",
    "WR2": "Jalen Coker",
    "WR3": "Xavier Legette",
    "LT1": "Ikem Ekwonu",
    "LG1": "Damien Lewis",
    "C1": "Cade Mays",
    "RG1": "Robert Hunt",
    "RT1": "Taylor Moton",
    "QB1": "Bryce Young",
    "QB2": "Andy Dalton",
    "TE1": "Ja'Tavion Sanders",
    "TE2": "Tommy Tremble",
    "RB1": "Chuba Hubbard",
    "RB2": "Rico Dowdle"
  },
  "CHI": {
    "DE1": "Montez Sweat",
    "DE2": "Joe Tryon-Shoyinka",
    "DT1": "Grady Jarrett",
    "DT2": "Shemar Turner",
    "LB1": "Tremaine Edmunds",
    "LB2": "Jalen Reeves-Maybin",
    "LB3": "Ruben Hyppolite II",
    "CB1": "Jaylon Johnson",
    "CB2": "Jaylon Jones",
    "SS1": "Jaquan Brisker",
    "FS1": "Kevin Byard III",
    "K1": "Cairo Santos",
    "WR1": "Rome Odunze",
    "WR2": "DJ Moore",
    "WR3": "Luther Burden III",
    "LT1": "Braxton Jones",
    "LG1": "Joe Thuney",
    "C1": "Drew Dalman",
    "RG1": "Jonah Jackson",
    "RT1": "Darnell Wright",
    "QB1": "Caleb Williams",
    "QB2": "Tyson Bagent",
    "TE1": "Colston Loveland",
    "TE2": "Cole Kmet",
    "RB1": "D'Andre Swift",
    "RB2": "Kyle Monangai"
  },
  "CIN": {
    "DE1": "Joseph Ossai",
    "DE2": "Shemar Stewart",
    "DT1": "T.J. Slaton Jr.",
    "DT2": "McKinnley Jackson",
    "LB1": "Demetrius Knight Jr.",
    "LB2": "Shaka Heyward",
    "LB3": "Barrett Carter",
    "CB1": "Dax Hill",
    "CB2": "DJ Ivey",
    "SS1": "Jordan Battle",
    "FS1": "Geno Stone",
    "K1": "Evan McPherson",
    "WR1": "Ja'Marr Chase",
    "WR2": "Tee Higgins",
    "WR3": "Andrei Iosivas",
    "LT1": "Orlando Brown Jr.",
    "LG1": "Cordell Volson",
    "C1": "Ted Karras",
    "RG1": "Dalton Risner",
    "RT1": "Amarius Mims",
    "QB1": "Joe Burrow",
    "QB2": "Joe Flacco",
    "TE1": "Mike Gesicki",
    "TE2": "Noah Fant",
    "RB1": "Chase Brown",
    "RB2": "Samaje Perine"
  },
  "CLE": {
    "DE1": "Alex Wright",
    "DE2": "Cameron Thomas",
    "DT1": "Maliek Collins",
    "DT2": "Shelby Harris",
    "LB1": "Jeremiah Owusu-Koramoah",
    "LB2": "Mohamoud Diabate",
    "LB3": "Carson Schwesinger",
    "CB1": "Denzel Ward",
    "CB2": "Sam Webb",
    "SS1": "Grant Delpit",
    "FS1": "Ronnie Hickman",
    "K1": "Andre Szmyt",
    "WR1": "Jerry Jeudy",
    "WR2": "Cedric Tillman",
    "WR3": "Isaiah Bond",
    "LT1": "Cam Robinson",
    "LG1": "Joel Bitonio",
    "C1": "Ethan Pocic",
    "RG1": "Wyatt Teller",
    "RT1": "Jack Conklin",
    "QB1": "Shedeur Sanders",
    "QB2": "Dillon Gabriel",
    "TE1": "Harold Fannin Jr.",
    "TE2": "David Njoku",
    "RB1": "Quinshon Judkins",
    "RB2": "Dylan Sampson"
  },
  "DAL": {
    "DE1": "Donovan Ezeiruaku",
    "DE2": "Sam Williams",
    "DT1": "Osa Odighizuwa",
    "DT2": "Kenny Clark",
    "LB1": "DeMarvion Overshown",
    "LB2": "Marist Liufau",
    "LB3": "Shemar James",
    "CB1": "Shavon Revel Jr.",
    "CB2": "Trikweze Bridges",
    "SS1": "Donovan Wilson",
    "FS1": "Malik Hooker",
    "K1": "Brandon Aubrey",
    "WR1": "CeeDee Lamb",
    "WR2": "George Pickens",
    "WR3": "Ryan Flournoy",
    "LT1": "Tyler Smith",
    "LG1": "T.J. Bass",
    "C1": "Cooper Beebe",
    "RG1": "Tyler Booker",
    "RT1": "Terence Steele",
    "QB1": "Dak Prescott",
    "QB2": "Joe Milton III",
    "TE1": "Jake Ferguson",
    "TE2": "Brevyn Spann-Ford",
    "RB1": "Javonte Williams",
    "RB2": "Malik Davis"
  },
  "DEN": {
    "DE1": "Zach Allen",
    "DE2": "Jordan Jackson",
    "DT1": "D.J. Jones",
    "DT2": "Eyioma Uwazurike",
    "LB1": "Jonathon Cooper",
    "LB2": "Jonah Elliss",
    "LB3": "Que Robinson",
    "CB1": "Pat Surtain II",
    "CB2": "Kris Abrams-Draine",
    "SS1": "Talanoa Hufanga",
    "FS1": "Brandon Jones",
    "K1": "Wil Lutz",
    "WR1": "Courtland Sutton",
    "WR2": "Troy Franklin",
    "WR3": "Pat Bryant",
    "LT1": "Garett Bolles",
    "LG1": "Ben Powers",
    "C1": "Luke Wattenberg",
    "RG1": "Quinn Meinerz",
    "RT1": "Mike McGlinchey",
    "QB1": "Bo Nix",
    "QB2": "Jarrett Stidham",
    "TE1": "Evan Engram",
    "TE2": "Adam Trautman",
    "RB1": "J.K. Dobbins",
    "RB2": "RJ Harvey"
  },
  "DET": {
    "DE1": "Aidan Hutchinson",
    "DE2": "Tyrus Wheat",
    "DT1": "Alim McNeill",
    "DT2": "Tyleik Williams",
    "LB1": "Alex Anzalone",
    "LB2": "Malcolm Rodriguez",
    "LB3": "Trevor Nowaske",
    "CB1": "Rock Ya-Sin",
    "CB2": "Nick Whiteside",
    "SS1": "Avonte Maddox",
    "FS1": "Thomas Harper",
    "K1": "Jake Bates",
    "WR1": "Amon-Ra St. Brown",
    "WR2": "Jameson Williams",
    "WR3": "Isaac TeSlaa",
    "LT1": "Taylor Decker",
    "LG1": "Christian Mahogany",
    "C1": "Graham Glasgow",
    "RG1": "Tate Ratledge",
    "RT1": "Penei Sewell",
    "QB1": "Jared Goff",
    "QB2": "Kyle Allen",
    "TE1": "Shane Zylstra",
    "TE2": "Anthony Firkser",
    "RB1": "Jahmyr Gibbs",
    "RB2": "David Montgomery"
  },
  "GB": {
    "DE1": "Rashan Gary",
    "DE2": "Arron Mosby",
    "DT1": "Colby Wooden",
    "DT2": "Jordon Riley",
    "LB1": "Edgerrin Cooper",
    "LB2": "Nick Niemann",
    "LB3": "Kristian Welch",
    "CB1": "Keisean Nixon",
    "CB2": "Nate Hobbs",
    "SS1": "Evan Williams",
    "FS1": "Xavier McKinney",
    "K1": "Brandon McManus",
    "WR1": "Christian Watson",
    "WR2": "Romeo Doubs",
    "WR3": "Jayden Reed",
    "LT1": "Rasheed Walker",
    "LG1": "Aaron Banks",
    "C1": "Elgton Jenkins",
    "RG1": "Anthony Belton",
    "RT1": "Zach Tom",
    "QB1": "Jordan Love",
    "QB2": "Malik Willis",
    "TE1": "Tucker Kraft",
    "TE2": "John FitzPatrick",
    "RB1": "Josh Jacobs",
    "RB2": "Emanuel Wilson"
  },
  "HOU": {
    "DE1": "Danielle Hunter",
    "DE2": "Denico Autry",
    "DT1": "Tommy Togiai",
    "DT2": "Folorunso Fatukasi",
    "LB1": "Henry To'oTo'o",
    "LB2": "Jake Hansen",
    "LB3": "Damone Clark",
    "CB1": "Derek Stingley Jr.",
    "CB2": "Tremon Smith",
    "SS1": "Calen Bullock",
    "FS1": "Jaylen Reed",
    "K1": "Ka'imi Fairbairn",
    "WR1": "Nico Collins",
    "WR2": "Jayden Higgins",
    "WR3": "Christian Kirk",
    "LT1": "Aireontae Ersery",
    "LG1": "Jarrett Patterson",
    "C1": "Jake Andrews",
    "RG1": "Ed Ingram",
    "RT1": "Trent Brown",
    "QB1": "C.J. Stroud",
    "QB2": "Davis Mills",
    "TE1": "Dalton Schultz",
    "TE2": "Brevin Jordan",
    "RB1": "Woody Marks",
    "RB2": "Joe Mixon"
  },
  "IND": {
    "DE1": "Kwity Paye",
    "DE2": "Tyquan Lewis",
    "DT1": "Grover Stewart",
    "DT2": "Adetomiwa Adebawore",
    "LB1": "Germaine Pratt",
    "LB2": "Segun Olubi",
    "LB3": "Jaylon Carlies",
    "CB1": "Sauce Gardner",
    "CB2": "Justin Walley",
    "SS1": "Nick Cross",
    "FS1": "Cam Bynum",
    "K1": "Blake Grupe",
    "WR1": "Michael Pittman Jr.",
    "WR2": "Alec Pierce",
    "WR3": "Josh Downs",
    "LT1": "Bernhard Raimann",
    "LG1": "Quenton Nelson",
    "C1": "Tanor Bortolini",
    "RG1": "Matt Goncalves",
    "RT1": "Braden Smith",
    "QB1": "Daniel Jones",
    "QB2": "Anthony Richardson Sr.",
    "TE1": "Tyler Warren",
    "TE2": "Mo Alie-Cox",
    "RB1": "Jonathan Taylor",
    "RB2": "Ameer Abdullah"
  },
  "JAX": {
    "DE1": "Josh Hines-Allen",
    "DE2": "Dawuane Smoot",
    "DT1": "DaVon Hamilton",
    "DT2": "Matt Dickerson",
    "LB1": "Foyesade Oluokun",
    "LB2": "Jalen McLeod",
    "LB3": "Branson Combs",
    "CB1": "Jarrian Jones",
    "CB2": "Keith Taylor",
    "SS1": "Eric Murray",
    "FS1": "Andrew Wingard",
    "K1": "Cam Little",
    "WR1": "Brian Thomas Jr.",
    "WR2": "Jakobi Meyers",
    "WR3": "Parker Washington",
    "LT1": "Cole Van Lanen",
    "LG1": "Ezra Cleveland",
    "C1": "Robert Hainsey",
    "RG1": "Patrick Mekari",
    "RT1": "Anton Harrison",
    "QB1": "Trevor Lawrence",
    "QB2": "Nick Mullens",
    "TE1": "Brenton Strange",
    "TE2": "Johnny Mundt",
    "RB1": "Travis Etienne Jr.",
    "RB2": "Bhayshul Tuten"
  },
  "KC": {
    "DE1": "George Karlaftis",
    "DE2": "Charles Omenihu",
    "DT1": "Chris Jones",
    "DT2": "Jerry Tillery",
    "LB1": "Drue Tranquill",
    "LB2": "Jeffrey Bassa",
    "LB3": "Kam Arnold",
    "CB1": "Trent McDuffie",
    "CB2": "Nohl Williams",
    "SS1": "Chamarri Conner",
    "FS1": "Bryan Cook",
    "K1": "Harrison Butker",
    "WR1": "Rashee Rice",
    "WR2": "Xavier Worthy",
    "WR3": "Hollywood Brown",
    "LT1": "Josh Simmons",
    "LG1": "Kingsley Suamataia",
    "C1": "Creed Humphrey",
    "RG1": "Trey Smith",
    "RT1": "Jawaan Taylor",
    "QB1": "Patrick Mahomes",
    "QB2": "Gardner Minshew",
    "TE1": "Travis Kelce",
    "TE2": "Noah Gray",
    "RB1": "Isiah Pacheco",
    "RB2": "Kareem Hunt"
  },
  "LV": {
    "DE1": "Maxx Crosby",
    "DE2": "Tyree Wilson",
    "DT1": "Jonah Laulu",
    "DT2": "Thomas Booker IV",
    "LB1": "Jamal Adams",
    "LB2": "Jon Rhattigan",
    "LB3": "Elandon Roberts",
    "CB1": "Darien Porter",
    "CB2": "Kyu Blu Kelly",
    "SS1": "Jeremy Chinn",
    "FS1": "Isaiah Pola-Mao",
    "K1": "Daniel Carlson",
    "WR1": "Tre Tucker",
    "WR2": "Jack Bech",
    "WR3": "Dont'e Thornton Jr.",
    "LT1": "Kolton Miller",
    "LG1": "Dylan Parham",
    "C1": "Alex Cappa",
    "RG1": "Jackson Powers-Johnson",
    "RT1": "DJ Glaze",
    "QB1": "Geno Smith",
    "QB2": "Kenny Pickett",
    "TE1": "Brock Bowers",
    "TE2": "Michael Mayer",
    "RB1": "Ashton Jeanty",
    "RB2": "Raheem Mostert"
  },
  "LAC": {
    "DE1": "Da'Shawn Hand",
    "DE2": "Scott Matlock",
    "DT1": "Teair Tart",
    "DT2": "Jamaree Caldwell",
    "LB1": "Tuli Tuipulotu",
    "LB2": "Bud Dupree",
    "LB3": "Kyle Kennard",
    "CB1": "Donte Jackson",
    "CB2": "Deane Leonard",
    "SS1": "Derwin James Jr.",
    "FS1": "Elijah Molden",
    "K1": "Cameron Dicker",
    "WR1": "Ladd McConkey",
    "WR2": "Quentin Johnston",
    "WR3": "Keenan Allen",
    "LT1": "Rashawn Slater",
    "LG1": "Zion Johnson",
    "C1": "Bradley Bozeman",
    "RG1": "Mekhi Becton",
    "RT1": "Joe Alt",
    "QB1": "Justin Herbert",
    "QB2": "Trey Lance",
    "TE1": "Oronde Gadsden",
    "TE2": "Tucker Fisk",
    "RB1": "Omarion Hampton",
    "RB2": "Kimani Vidal"
  },
  "LAR": {
    "DE1": "Braden Fiske",
    "DE2": "Desjuan Johnson",
    "DT1": "Poona Ford",
    "DT2": "Ty Hamilton",
    "LB1": "Byron Young",
    "LB2": "Josaiah Stewart",
    "LB3": "Nate Landman",
    "CB1": "Cobie Durant",
    "CB2": "Emmanuel Forbes Jr.",
    "SS1": "Kam Curl",
    "FS1": "Kamren Kinchens",
    "K1": "Harrison Mevis",
    "WR1": "Puka Nacua",
    "WR2": "Davante Adams",
    "WR3": "Konata Mumpfield",
    "LT1": "Alaric Jackson",
    "LG1": "Steve Avila",
    "C1": "Coleman Shelton",
    "RG1": "Kevin Dotson",
    "RT1": "Warren McClendon Jr.",
    "QB1": "Matthew Stafford",
    "QB2": "Jimmy Garoppolo",
    "TE1": "Colby Parkinson",
    "TE2": "Tyler Higbee",
    "RB1": "Kyren Williams",
    "RB2": "Blake Corum"
  },
  "MIA": {
    "DE1": "Chop Robinson",
    "DE2": "Derrick McLendon",
    "DT1": "Zach Sieler",
    "DT2": "Kenneth Grant",
    "LB1": "Jordyn Brooks",
    "LB2": "Willie Gay Jr.",
    "LB3": "Jordan Colbert",
    "CB1": "Jack Jones",
    "CB2": "JuJu Brents",
    "SS1": "Ashtyn Davis",
    "FS1": "Minkah Fitzpatrick",
    "K1": "Jason Sanders",
    "WR1": "Jaylen Waddle",
    "WR2": "Malik Washington",
    "WR3": "Cedrick Wilson Jr.",
    "LT1": "Patrick Paul",
    "LG1": "Jonah Savaiinaea",
    "C1": "Aaron Brewer",
    "RG1": "Cole Strange",
    "RT1": "Austin Jackson",
    "QB1": "Quinn Ewers",
    "QB2": "Zach Wilson",
    "TE1": "Darren Waller",
    "TE2": "Greg Dulcich",
    "RB1": "De'Von Achane",
    "RB2": "Jaylen Wright"
  },
  "MIN": {
    "DE1": "Jonathan Allen",
    "DE2": "Levi Drake Rodriguez",
    "DT1": "Jalen Redmond",
    "DT2": "Taki Taimani",
    "LB1": "Jonathan Greenard",
    "LB2": "Dallas Turner",
    "LB3": "Chaz Chambliss",
    "CB1": "Isaiah Rodgers",
    "CB2": "Dwight McGlothern",
    "SS1": "Joshua Metellus",
    "FS1": "Harrison Smith",
    "K1": "Will Reichard",
    "WR1": "Justin Jefferson",
    "WR2": "Jordan Addison",
    "WR3": "Jalen Nailor",
    "LT1": "Christian Darrisaw",
    "LG1": "Donovan Jackson",
    "C1": "Ryan Kelly",
    "RG1": "Will Fries",
    "RT1": "Brian O'Neill",
    "QB1": "J.J. McCarthy",
    "QB2": "Carson Wentz",
    "TE1": "T.J. Hockenson",
    "TE2": "Josh Oliver",
    "RB1": "Aaron Jones Sr.",
    "RB2": "Jordan Mason"
  },
  "NE": {
    "DE1": "Christian Barmore",
    "DE2": "Joshua Farmer",
    "DT1": "Khyiris Tonga",
    "DT2": "Eric Gregory",
    "LB1": "Harold Landry III",
    "LB2": "Elijah Ponder",
    "LB3": "Amari Gainer",
    "CB1": "Carlton Davis III",
    "CB2": "Charles Woods",
    "SS1": "Jaylinn Hawkins",
    "FS1": "Craig Woodson",
    "K1": "Andy Borregales",
    "WR1": "Stefon Diggs",
    "WR2": "Kayshon Boutte",
    "WR3": "Mack Hollins",
    "LT1": "Will Campbell",
    "LG1": "Jared Wilson",
    "C1": "Garrett Bradbury",
    "RG1": "Mike Onwenu",
    "RT1": "Morgan Moses",
    "QB1": "Drake Maye",
    "QB2": "Joshua Dobbs",
    "TE1": "Hunter Henry",
    "TE2": "Austin Hooper",
    "RB1": "Rhamondre Stevenson",
    "RB2": "TreVeyon Henderson"
  },
  "NO": {
    "DE1": "Cameron Jordan",
    "DE2": "Vernon Broughton",
    "DT1": "Davon Godchaux",
    "DT2": "Khristian Boyd",
    "LB1": "Carl Granderson",
    "LB2": "Jonah Williams",
    "LB3": "Fadil Diggs",
    "CB1": "Kool-Aid McKinstry",
    "CB2": "Michael Davis",
    "SS1": "Justin Reid",
    "FS1": "Julian Blackmon",
    "K1": "Charlie Smyth",
    "WR1": "Chris Olave",
    "WR2": "Devaughn Vele",
    "WR3": "Mason Tipton",
    "LT1": "Kelvin Banks Jr.",
    "LG1": "Dillon Radunz",
    "C1": "Erik McCoy",
    "RG1": "Cesar Ruiz",
    "RT1": "Taliese Fuaga",
    "QB1": "Tyler Shough",
    "QB2": "Spencer Rattler",
    "TE1": "Juwan Johnson",
    "TE2": "Foster Moreau",
    "RB1": "Alvin Kamara",
    "RB2": "Kendre Miller"
  },
  "NYG": {
    "DE1": "Rakeem Nunez-Roches",
    "DE2": "Darius Alexander",
    "DT1": "Dexter Lawrence II",
    "DT2": "D.J. Davidson",
    "LB1": "Brian Burns",
    "LB2": "Abdul Carter",
    "LB3": "Victor Dimukeje",
    "CB1": "Paulson Adebo",
    "CB2": "Deonte Banks",
    "SS1": "Tyler Nubin",
    "FS1": "Jevon Holland",
    "K1": "Graham Gano",
    "WR1": "Malik Nabers",
    "WR2": "Wan'Dale Robinson",
    "WR3": "Darius Slayton",
    "LT1": "Andrew Thomas",
    "LG1": "Jon Runyan",
    "C1": "John Michael Schmitz Jr.",
    "RG1": "Greg Van Roten",
    "RT1": "Jermaine Eluemunor",
    "QB1": "Jaxson Dart",
    "QB2": "Jameis Winston",
    "TE1": "Theo Johnson",
    "TE2": "Daniel Bellinger",
    "RB1": "Cam Skattebo",
    "RB2": "Tyrone Tracy Jr."
  },
  "NYJ": {
    "DE1": "Will McDonald IV",
    "DE2": "Braiden McGregor",
    "DT1": "Harrison Phillips",
    "DT2": "Jowon Briggs",
    "LB1": "Kiko Mauigoa",
    "LB2": "Marcelino McCrary-Ball",
    "LB3": "Cam Jones",
    "CB1": "Azareye'h Thomas",
    "CB2": "Qwan'tez Stiggers",
    "SS1": "Malachi Moore",
    "FS1": "Andre Cisco",
    "K1": "Nick Folk",
    "WR1": "Garrett Wilson",
    "WR2": "Josh Reynolds",
    "WR3": "John Metchie III",
    "LT1": "Olu Fashanu",
    "LG1": "John Simpson",
    "C1": "Josh Myers",
    "RG1": "Alijah Vera-Tucker",
    "RT1": "Armand Membou",
    "QB1": "Justin Fields",
    "QB2": "Tyrod Taylor",
    "TE1": "Mason Taylor",
    "TE2": "Jeremy Ruckert",
    "RB1": "Breece Hall",
    "RB2": "Braelon Allen"
  },
  "PHI": {
    "DE1": "Moro Ojomo",
    "DE2": "Byron Young",
    "DT1": "Jordan Davis",
    "LB1": "Jaelan Phillips",
    "LB2": "Azeez Ojulari",
    "LB3": "Brandon Graham",
    "CB1": "Adoree' Jackson",
    "CB2": "Kelee Ringo",
    "SS1": "Reed Blankenship",
    "FS1": "Andrew Mukuba",
    "K1": "Jake Elliott",
    "WR1": "A.J. Brown",
    "WR2": "DeVonta Smith",
    "WR3": "Jahan Dotson",
    "LT1": "Jordan Mailata",
    "LG1": "Landon Dickerson",
    "C1": "Cam Jurgens",
    "RG1": "Tyler Steen",
    "RT1": "Lane Johnson",
    "QB1": "Jalen Hurts",
    "QB2": "Tanner McKee",
    "TE1": "Dallas Goedert",
    "TE2": "Grant Calcaterra",
    "RB1": "Saquon Barkley",
    "RB2": "Tank Bigsby"
  },
  "PIT": {
    "DE1": "Cameron Heyward",
    "DE2": "Isaiahh Loudermilk",
    "DT1": "Keeanu Benton",
    "DT2": "Yahya Black",
    "LB1": "T.J. Watt",
    "LB2": "Jack Sawyer",
    "LB3": "Jeremiah Moon",
    "CB1": "James Pierre",
    "CB2": "Asante Samuel Jr.",
    "SS1": "Kyle Dugger",
    "FS1": "Chuck Clark",
    "K1": "Chris Boswell",
    "WR1": "DK Metcalf",
    "WR2": "Calvin Austin III",
    "WR3": "Marquez Valdes-Scantling",
    "LT1": "Broderick Jones",
    "LG1": "Isaac Seumalo",
    "C1": "Zach Frazier",
    "RG1": "Mason McCormick",
    "RT1": "Troy Fautanu",
    "QB1": "Aaron Rodgers",
    "QB2": "Mason Rudolph",
    "TE1": "Pat Freiermuth",
    "TE2": "Jonnu Smith",
    "RB1": "Jaylen Warren",
    "RB2": "Kenneth Gainwell"
  },
  "SF": {
    "DE1": "Nick Bosa",
    "DE2": "Bryce Huff",
    "DT1": "Kalia Davis",
    "DT2": "Kevin Givens",
    "LB1": "Dee Winters",
    "LB2": "Curtis Robinson",
    "LB3": "Nick Martin",
    "CB1": "Renardo Green",
    "CB2": "Darrell Luter Jr.",
    "SS1": "Ji'Ayir Brown",
    "FS1": "Malik Mustapha",
    "K1": "Eddy Pineiro",
    "WR1": "Jauan Jennings",
    "WR2": "Ricky Pearsall",
    "WR3": "Demarcus Robinson",
    "LT1": "Trent Williams",
    "LG1": "Spencer Burford",
    "C1": "Jake Brendel",
    "RG1": "Dominick Puni",
    "RT1": "Colton McKivitz",
    "QB1": "Brock Purdy",
    "QB2": "Mac Jones",
    "TE1": "George Kittle",
    "TE2": "Jake Tonges",
    "RB1": "Christian McCaffrey",
    "RB2": "Brian Robinson Jr."
  },
  "SEA": {
    "DE1": "DeMarcus Lawrence",
    "DE2": "Boye Mafe",
    "DT1": "Byron Murphy II",
    "DT2": "Brandon Pili",
    "LB1": "Uchenna Nwosu",
    "LB2": "Boye Mafe",
    "LB3": "Ja'Markis Weston",
    "CB1": "Devon Witherspoon",
    "CB2": "Nehemiah Pritchett",
    "SS1": "Coby Bryant",
    "FS1": "Julian Love",
    "K1": "Jason Myers",
    "WR1": "Jaxon Smith-Njigba",
    "WR2": "Cooper Kupp",
    "WR3": "Rashid Shaheed",
    "LT1": "Charles Cross",
    "LG1": "Grey Zabel",
    "C1": "Jalen Sundell",
    "RG1": "Anthony Bradford",
    "RT1": "Abraham Lucas",
    "QB1": "Sam Darnold",
    "QB2": "Drew Lock",
    "TE1": "AJ Barner",
    "TE2": "Elijah Arroyo",
    "RB1": "Kenneth Walker III",
    "RB2": "Zach Charbonnet"
  },
  "TB": {
    "DE1": "Elijah Roberts",
    "DE2": "Calijah Kancey",
    "DT1": "Vita Vea",
    "DT2": "Elijah Simmons",
    "LB1": "Yaya Diaby",
    "LB2": "Chris Braswell",
    "LB3": "Benton Whitley",
    "CB1": "Jamel Dean",
    "CB2": "Josh Hayes",
    "SS1": "Antoine Winfield Jr.",
    "FS1": "Tykee Smith",
    "K1": "Chase McLaughlin",
    "WR1": "Mike Evans",
    "WR2": "Chris Godwin Jr.",
    "WR3": "Emeka Egbuka",
    "LT1": "Tristan Wirfs",
    "LG1": "Ben Bredeson",
    "C1": "Graham Barton",
    "RG1": "Cody Mauch",
    "RT1": "Luke Goedeke",
    "QB1": "Baker Mayfield",
    "QB2": "Teddy Bridgewater",
    "TE1": "Cade Otton",
    "TE2": "Payne Durham",
    "RB1": "Bucky Irving",
    "RB2": "Rachaad White"
  },
  "TEN": {
    "DE1": "Sebastian Joseph-Day",
    "DE2": "James Lynch",
    "DT1": "T'Vondre Sweat",
    "DT2": "Cam Horsley",
    "LB1": "Jihad Ward",
    "LB2": "Truman Jones",
    "LB3": "Ali Gaye",
    "CB1": "Darrell Baker Jr.",
    "CB2": "Micah Robinson",
    "SS1": "Amani Hooker",
    "FS1": "Xavier Woods",
    "K1": "Joey Slye",
    "WR1": "Calvin Ridley",
    "WR2": "Elic Ayomanor",
    "WR3": "Chimere Dike",
    "LT1": "Dan Moore Jr.",
    "LG1": "Peter Skoronski",
    "C1": "Lloyd Cushenberry III",
    "RG1": "Kevin Zeitler",
    "RT1": "JC Latham",
    "QB1": "Cam Ward",
    "QB2": "Will Levis",
    "TE1": "Chig Okonkwo",
    "TE2": "Gunnar Helm",
    "RB1": "Tony Pollard",
    "RB2": "Tyjae Spears"
  },
  "WAS": {
    "DE1": "Dorance Armstrong",
    "DE2": "Jalyn Holmes",
    "DT1": "Daron Payne",
    "DT2": "Eddie Goldman",
    "LB1": "Frankie Luvu",
    "LB2": "Jordan Magee",
    "LB3": "Nick Bellore",
    "CB1": "Trey Amos",
    "CB2": "Antonio Hamilton Sr.",
    "SS1": "Jeremy Reaves",
    "FS1": "Will Harris",
    "K1": "Jake Moody",
    "WR1": "Terry McLaurin",
    "WR2": "Deebo Samuel",
    "WR3": "Luke McCaffrey",
    "LT1": "Laremy Tunsil",
    "LG1": "Chris Paul",
    "C1": "Tyler Biadasz",
    "RG1": "Sam Cosmi",
    "RT1": "Josh Conerly Jr.",
    "QB1": "Jayden Daniels",
    "QB2": "Marcus Mariota",
    "TE1": "Zach Ertz",
    "TE2": "Ben Sinnott",
    "RB1": "Chris Rodriguez Jr.",
    "RB2": "Jacory Croskey-Merritt"
  }
};

export default NFL_ROSTERS;
