// NFL Rosters — auto-generated from ESPN depth charts on 2026-03-17
// Run: node src/updateRosters.js to refresh

const NFL_ROSTERS = {
  "ARI": {
    "QB1": "Jacoby Brissett",
    "QB2": "Gardner Minshew",
    "RB1": "James Conner",
    "RB2": "Tyler Allgeier",
    "WR1": "Marvin Harrison Jr.",
    "WR2": "Michael Wilson",
    "WR3": "Kendrick Bourne",
    "TE1": "Trey McBride",
    "TE2": "Tip Reiman",
    "LT": "Paris Johnson Jr.",
    "LG": "Isaac Seumalo",
    "C": "Hjalte Froholdt",
    "RG": "Isaiah Adams",
    "RT": "Elijah Wilkinson",
    "DE1": "Josh Sweat",
    "DT1": "Roy Lopez",
    "DE2": "Darius Robinson",
    "LB1": "Cody Simon",
    "LB2": "Mack Wilson Sr.",
    "LB4": "Zaven Collins",
    "CB1": "Will Johnson",
    "CB2": "Denzel Burke",
    "NB": "Garrett Williams",
    "SS": "Budda Baker",
    "FS": "Andrew Wingard",
    "K": "Chad Ryland"
  },
  "ATL": {
    "QB1": "Michael Penix Jr.",
    "QB2": "Tua Tagovailoa",
    "RB1": "Bijan Robinson",
    "RB2": "Nathan Carter",
    "WR1": "Drake London",
    "WR2": "Jahan Dotson",
    "WR3": "Olamide Zaccheaus",
    "TE1": "Kyle Pitts Sr.",
    "TE2": "Austin Hooper",
    "LT": "Jake Matthews",
    "LG": "Matthew Bergeron",
    "C": "Ryan Neuzil",
    "RG": "Chris Lindstrom",
    "RT": "Kaleb McGary",
    "DE1": "Brandon Dorlus",
    "DT1": "Da'Shawn Hand",
    "DE2": "Zach Harrison",
    "LB1": "Jalon Walker",
    "LB2": "Divine Deablo",
    "LB3": "James Pearce Jr.",
    "DT2": "Ruke Orhorhoro",
    "CB1": "A.J. Terrell Jr.",
    "CB2": "Mike Hughes",
    "NB": "Billy Bowman Jr.",
    "SS": "Jessie Bates III",
    "FS": "Xavier Watts",
    "K": "Nick Folk"
  },
  "BAL": {
    "QB1": "Lamar Jackson",
    "QB2": "Tyler Huntley",
    "RB1": "Derrick Henry",
    "RB2": "Justice Hill",
    "WR1": "Zay Flowers",
    "WR2": "Rashod Bateman",
    "WR3": "Devontez Walker",
    "TE1": "Mark Andrews",
    "TE2": "Durham Smythe",
    "LT": "Ronnie Stanley",
    "LG": "Andrew Vorhees",
    "C": "Corey Bullock",
    "RG": "John Simpson",
    "RT": "Roger Rosengarten",
    "DE1": "Travis Jones",
    "DT1": "John Jenkins",
    "DE2": "Nnamdi Madubuike",
    "LB1": "Mike Green",
    "LB2": "Roquan Smith",
    "LB3": "Teddye Buchanan",
    "LB4": "Trey Hendrickson",
    "CB1": "Nate Wiggins",
    "CB2": "Marlon Humphrey",
    "NB": "Jaylinn Hawkins",
    "SS": "Kyle Hamilton",
    "FS": "Malaki Starks",
    "K": "Tyler Loop"
  },
  "BUF": {
    "QB1": "Josh Allen",
    "QB2": "Kyle Allen",
    "RB1": "James Cook III",
    "RB2": "Ty Johnson",
    "WR1": "DJ Moore",
    "WR2": "Khalil Shakir",
    "WR3": "Joshua Palmer",
    "TE1": "Dalton Kincaid",
    "TE2": "Dawson Knox",
    "LT": "Dion Dawkins",
    "LG": "Alec Anderson",
    "C": "Connor McGovern",
    "RG": "O'Cyrus Torrence",
    "RT": "Spencer Brown",
    "DE1": "Ed Oliver",
    "DT1": "Deone Walker",
    "DE2": "T.J. Sanders",
    "LB1": "Greg Rousseau",
    "LB2": "Joe Andreessen",
    "LB3": "Terrel Bernard",
    "LB4": "Bradley Chubb",
    "CB1": "Dorian Strong",
    "CB2": "Christian Benford",
    "NB": "C.J. Gardner-Johnson",
    "SS": "Geno Stone",
    "FS": "Cole Bishop",
    "K": "Tyler Bass"
  },
  "CAR": {
    "QB1": "Bryce Young",
    "QB2": "Kenny Pickett",
    "RB1": "Chuba Hubbard",
    "RB2": "Jonathon Brooks",
    "WR1": "Tetairoa McMillan",
    "WR2": "Jalen Coker",
    "WR3": "Xavier Legette",
    "TE1": "Ja'Tavion Sanders",
    "TE2": "Tommy Tremble",
    "LT": "Ikem Ekwonu",
    "LG": "Damien Lewis",
    "C": "Luke Fortner",
    "RG": "Robert Hunt",
    "RT": "Taylor Moton",
    "DE1": "Derrick Brown",
    "DT1": "Bobby Brown III",
    "DE2": "Tershawn Wharton",
    "LB1": "Nic Scourton",
    "LB2": "Devin Lloyd",
    "LB3": "Trevin Wallace",
    "LB4": "Jaelan Phillips",
    "CB1": "Mike Jackson",
    "CB2": "Jaycee Horn",
    "NB": "Chau Smith-Wade",
    "SS": "Tre'von Moehrig",
    "FS": "Nick Scott",
    "K": "Ryan Fitzgerald"
  },
  "CHI": {
    "QB1": "Caleb Williams",
    "QB2": "Tyson Bagent",
    "RB1": "D'Andre Swift",
    "RB2": "Kyle Monangai",
    "WR1": "Rome Odunze",
    "WR2": "Luther Burden III",
    "WR3": "Jahdae Walker",
    "TE1": "Colston Loveland",
    "TE2": "Cole Kmet",
    "LT": "Braxton Jones",
    "LG": "Joe Thuney",
    "C": "Garrett Bradbury",
    "RG": "Jonah Jackson",
    "RT": "Darnell Wright",
    "DE1": "Montez Sweat",
    "DT1": "Grady Jarrett",
    "DT2": "Gervon Dexter Sr.",
    "DE2": "Dayo Odeyingbo",
    "LB1": "Devin Bush",
    "LB2": "T.J. Edwards",
    "LB3": "D'Marco Jackson",
    "CB1": "Jaylon Johnson",
    "CB2": "Tyrique Stevenson",
    "NB": "Kyler Gordon",
    "SS": "Cam Lewis",
    "FS": "Coby Bryant",
    "K": "Cairo Santos"
  },
  "CIN": {
    "QB1": "Joe Burrow",
    "QB2": "Josh Johnson",
    "RB1": "Chase Brown",
    "RB2": "Samaje Perine",
    "WR1": "Ja'Marr Chase",
    "WR2": "Tee Higgins",
    "WR3": "Andrei Iosivas",
    "TE1": "Mike Gesicki",
    "TE2": "Erick All Jr.",
    "LT": "Orlando Brown Jr.",
    "LG": "Dylan Fairchild",
    "C": "Ted Karras",
    "RG": "Dalton Risner",
    "RT": "Amarius Mims",
    "DE1": "Boye Mafe",
    "DT1": "Jonathan Allen",
    "DT2": "B.J. Hill",
    "DE2": "Myles Murphy",
    "LB1": "Demetrius Knight Jr.",
    "LB2": "Oren Burks",
    "CB1": "Dax Hill",
    "CB2": "DJ Turner II",
    "NB": "Jalen Davis",
    "SS": "Jordan Battle",
    "FS": "Bryan Cook",
    "K": "Evan McPherson"
  },
  "CLE": {
    "QB1": "Shedeur Sanders",
    "QB2": "Dillon Gabriel",
    "RB1": "Quinshon Judkins",
    "RB2": "Dylan Sampson",
    "WR1": "Jerry Jeudy",
    "WR2": "Cedric Tillman",
    "WR3": "Isaiah Bond",
    "TE1": "Harold Fannin Jr.",
    "TE2": "Jack Stoll",
    "LT": "Dawand Jones",
    "LG": "Zion Johnson",
    "C": "Elgton Jenkins",
    "RG": "Teven Jenkins",
    "RT": "Tytus Howard",
    "DE1": "Alex Wright",
    "DT1": "Maliek Collins",
    "DT2": "Mason Graham",
    "DE2": "Myles Garrett",
    "LB1": "Jeremiah Owusu-Koramoah",
    "LB2": "Quincy Williams",
    "CB1": "Denzel Ward",
    "CB2": "Tyson Campbell",
    "NB": "Myles Harden",
    "SS": "Grant Delpit",
    "FS": "Ronnie Hickman",
    "K": "Andre Szmyt"
  },
  "DAL": {
    "QB1": "Dak Prescott",
    "QB2": "Joe Milton III",
    "RB1": "Javonte Williams",
    "RB2": "Malik Davis",
    "WR1": "CeeDee Lamb",
    "WR2": "George Pickens",
    "WR3": "Ryan Flournoy",
    "TE1": "Jake Ferguson",
    "TE2": "Brevyn Spann-Ford",
    "LT": "Tyler Smith",
    "LG": "T.J. Bass",
    "C": "Cooper Beebe",
    "RG": "Tyler Booker",
    "RT": "Terence Steele",
    "DE1": "Quinnen Williams",
    "DT1": "Otito Ogbonnia",
    "DE2": "Kenny Clark",
    "LB1": "Rashan Gary",
    "LB2": "DeMarvion Overshown",
    "LB3": "Shemar James",
    "LB4": "Donovan Ezeiruaku",
    "CB1": "Shavon Revel Jr.",
    "CB2": "DaRon Bland",
    "NB": "Reddy Steward",
    "SS": "Jalen Thompson",
    "FS": "Malik Hooker",
    "K": "Brandon Aubrey"
  },
  "DEN": {
    "QB1": "Bo Nix",
    "QB2": "Jarrett Stidham",
    "RB1": "J.K. Dobbins",
    "RB2": "RJ Harvey",
    "WR1": "Jaylen Waddle",
    "WR2": "Courtland Sutton",
    "WR3": "Troy Franklin",
    "TE1": "Evan Engram",
    "TE2": "Adam Trautman",
    "LT": "Garett Bolles",
    "LG": "Ben Powers",
    "C": "Luke Wattenberg",
    "RG": "Quinn Meinerz",
    "RT": "Mike McGlinchey",
    "DE1": "Zach Allen",
    "DT1": "D.J. Jones",
    "DE2": "Malcolm Roach",
    "LB1": "Jonathon Cooper",
    "LB2": "Alex Singleton",
    "LB3": "Justin Strnad",
    "LB4": "Nik Bonitto",
    "CB1": "Pat Surtain II",
    "CB2": "Riley Moss",
    "NB": "Ja'Quan McMillian",
    "SS": "Talanoa Hufanga",
    "FS": "Brandon Jones",
    "K": "Wil Lutz"
  },
  "DET": {
    "QB1": "Jared Goff",
    "QB2": "Teddy Bridgewater",
    "RB1": "Jahmyr Gibbs",
    "RB2": "Isiah Pacheco",
    "WR1": "Amon-Ra St. Brown",
    "WR2": "Jameson Williams",
    "WR3": "Isaac TeSlaa",
    "TE1": "Sam LaPorta",
    "TE2": "Brock Wright",
    "LT": "Larry Borom",
    "LG": "Christian Mahogany",
    "C": "Cade Mays",
    "RG": "Tate Ratledge",
    "RT": "Penei Sewell",
    "DE1": "Aidan Hutchinson",
    "DT1": "Alim McNeill",
    "DT2": "Levi Onwuzurike",
    "DE2": "Tyler Lacy",
    "LB1": "Malcolm Rodriguez",
    "LB2": "Jack Campbell",
    "LB3": "Derrick Barnes",
    "CB1": "D.J. Reed",
    "CB2": "Terrion Arnold",
    "NB": "Ennis Rakestraw Jr.",
    "SS": "Brian Branch",
    "FS": "Kerby Joseph",
    "K": "Jake Bates"
  },
  "GB": {
    "QB1": "Jordan Love",
    "QB2": "Desmond Ridder",
    "RB1": "Josh Jacobs",
    "RB2": "Chris Brooks",
    "WR1": "Christian Watson",
    "WR2": "Jayden Reed",
    "WR3": "Matthew Golden",
    "TE1": "Tucker Kraft",
    "TE2": "Luke Musgrave",
    "LT": "Jordan Morgan",
    "LG": "Aaron Banks",
    "C": "Sean Rhyan",
    "RG": "Anthony Belton",
    "RT": "Zach Tom",
    "DE1": "Karl Brooks",
    "DT1": "Devonte Wyatt",
    "DE2": "Javon Hargrave",
    "LB1": "Brenton Cox Jr.",
    "LB2": "Edgerrin Cooper",
    "LB3": "Zaire Franklin",
    "LB4": "Micah Parsons",
    "CB1": "Keisean Nixon",
    "CB2": "Carrington Valentine",
    "NB": "Javon Bullard",
    "SS": "Evan Williams",
    "FS": "Xavier McKinney",
    "K": "Brandon McManus"
  },
  "HOU": {
    "QB1": "C.J. Stroud",
    "QB2": "Davis Mills",
    "RB1": "David Montgomery",
    "RB2": "Woody Marks",
    "WR1": "Nico Collins",
    "WR2": "Jayden Higgins",
    "WR3": "Tank Dell",
    "TE1": "Dalton Schultz",
    "TE2": "Brevin Jordan",
    "LT": "Aireontae Ersery",
    "LG": "Evan Brown",
    "C": "Jake Andrews",
    "RG": "Wyatt Teller",
    "RT": "Braden Smith",
    "DE1": "Danielle Hunter",
    "DT1": "Tommy Togiai",
    "DT2": "Sheldon Rankins",
    "DE2": "Will Anderson Jr.",
    "LB1": "Henry To'oTo'o",
    "LB2": "E.J. Speed",
    "CB1": "Derek Stingley Jr.",
    "CB2": "Kamari Lassiter",
    "NB": "Jalen Pitre",
    "SS": "Reed Blankenship",
    "FS": "Calen Bullock",
    "K": "Ka'imi Fairbairn"
  },
  "IND": {
    "QB1": "Daniel Jones",
    "QB2": "Anthony Richardson Sr.",
    "RB1": "Jonathan Taylor",
    "RB2": "DJ Giddens",
    "WR1": "Alec Pierce",
    "WR2": "Josh Downs",
    "WR3": "Ashton Dulin",
    "TE1": "Tyler Warren",
    "TE2": "Mo Alie-Cox",
    "LT": "Bernhard Raimann",
    "LG": "Quenton Nelson",
    "C": "Tanor Bortolini",
    "RG": "Matt Goncalves",
    "RT": "Jalen Travis",
    "DE1": "JT Tuimoloau",
    "DT1": "Grover Stewart",
    "DT2": "DeForest Buckner",
    "DE2": "Laiatu Latu",
    "LB1": "Jaylon Carlies",
    "LB2": "John Bullock",
    "CB1": "Sauce Gardner",
    "CB2": "Charvarius Ward",
    "NB": "Kenny Moore II",
    "SS": "Juanyeh Thomas",
    "FS": "Cam Bynum",
    "K": "Blake Grupe"
  },
  "JAX": {
    "QB1": "Trevor Lawrence",
    "QB2": "Nick Mullens",
    "RB1": "Bhayshul Tuten",
    "RB2": "Chris Rodriguez Jr.",
    "WR1": "Brian Thomas Jr.",
    "WR2": "Jakobi Meyers",
    "WR3": "Parker Washington",
    "TE1": "Brenton Strange",
    "TE2": "Quintin Morris",
    "LT": "Cole Van Lanen",
    "LG": "Ezra Cleveland",
    "C": "Robert Hainsey",
    "RG": "Patrick Mekari",
    "RT": "Anton Harrison",
    "DE1": "Josh Hines-Allen",
    "DT1": "DaVon Hamilton",
    "DT2": "Arik Armstead",
    "DE2": "Travon Walker",
    "LB1": "Foyesade Oluokun",
    "LB2": "Ventrell Miller",
    "LB3": "Dennis Gardeck",
    "CB1": "Travis Hunter",
    "CB2": "Christian Braswell",
    "NB": "Jourdan Lewis",
    "SS": "Eric Murray",
    "FS": "Antonio Johnson",
    "K": "Cam Little"
  },
  "KC": {
    "QB1": "Patrick Mahomes",
    "QB2": "Justin Fields",
    "RB1": "Kenneth Walker III",
    "RB2": "Emari Demercado",
    "WR1": "Rashee Rice",
    "WR2": "Xavier Worthy",
    "WR3": "Tyquan Thornton",
    "TE1": "Travis Kelce",
    "TE2": "Noah Gray",
    "LT": "Josh Simmons",
    "LG": "Kingsley Suamataia",
    "C": "Creed Humphrey",
    "RG": "Trey Smith",
    "RT": "Jaylon Moore",
    "DE1": "George Karlaftis",
    "DT1": "Chris Jones",
    "DT2": "Khyiris Tonga",
    "DE2": "Felix Anudike-Uzomah",
    "LB1": "Drue Tranquill",
    "LB2": "Cooper McDonald",
    "CB1": "Kader Kohou",
    "CB2": "Kristian Fulton",
    "NB": "Chris Roland-Wallace",
    "SS": "Chamarri Conner",
    "FS": "Alohi Gilman",
    "K": "Harrison Butker"
  },
  "LV": {
    "QB1": "Aidan O'Connell",
    "RB1": "Ashton Jeanty",
    "RB2": "Dylan Laube",
    "WR1": "Tre Tucker",
    "WR2": "Jalen Nailor",
    "WR3": "Jack Bech",
    "TE1": "Brock Bowers",
    "TE2": "Michael Mayer",
    "LT": "Kolton Miller",
    "LG": "Jordan Meredith",
    "C": "Tyler Linderbaum",
    "RG": "Jackson Powers-Johnson",
    "RT": "DJ Glaze",
    "DE1": "Thomas Booker IV",
    "DT1": "Adam Butler",
    "DE2": "Jonah Laulu",
    "LB1": "Maxx Crosby",
    "LB2": "Nakobe Dean",
    "LB3": "Quay Walker",
    "LB4": "Malcolm Koonce",
    "CB1": "Darien Porter",
    "CB2": "Eric Stokes",
    "NB": "Taron Johnson",
    "SS": "Jeremy Chinn",
    "FS": "Isaiah Pola-Mao",
    "K": "Matt Gay"
  },
  "LAC": {
    "QB1": "Justin Herbert",
    "QB2": "Trey Lance",
    "RB1": "Omarion Hampton",
    "RB2": "Kimani Vidal",
    "WR1": "Ladd McConkey",
    "WR2": "Quentin Johnston",
    "WR3": "Tre' Harris",
    "TE1": "Oronde Gadsden",
    "TE2": "Charlie Kolar",
    "LT": "Rashawn Slater",
    "LG": "Trevor Penning",
    "C": "Tyler Biadasz",
    "RG": "Cole Strange",
    "RT": "Joe Alt",
    "DE1": "Scott Matlock",
    "DT1": "Teair Tart",
    "DE2": "Justin Eboigbe",
    "LB1": "Daiyan Henley",
    "LB2": "Troy Dye",
    "DT2": "Dalvin Tomlinson",
    "CB1": "Donte Jackson",
    "CB2": "Cam Hart",
    "NB": "Tarheeb Still",
    "SS": "Derwin James Jr.",
    "FS": "Elijah Molden",
    "K": "Cameron Dicker"
  },
  "LAR": {
    "QB1": "Matthew Stafford",
    "QB2": "Stetson Bennett IV",
    "RB1": "Kyren Williams",
    "RB2": "Blake Corum",
    "WR1": "Puka Nacua",
    "WR2": "Davante Adams",
    "WR3": "Konata Mumpfield",
    "TE1": "Colby Parkinson",
    "TE2": "Tyler Higbee",
    "LT": "Alaric Jackson",
    "LG": "Steve Avila",
    "C": "Coleman Shelton",
    "RG": "Kevin Dotson",
    "RT": "Warren McClendon Jr.",
    "DE1": "Braden Fiske",
    "DT1": "Poona Ford",
    "DE2": "Kobie Turner",
    "LB1": "Byron Young",
    "LB2": "Nate Landman",
    "LB3": "Omar Speights",
    "LB4": "Jared Verse",
    "CB1": "Trent McDuffie",
    "CB2": "Jaylen Watson",
    "NB": "Quentin Lake",
    "SS": "Kam Curl",
    "FS": "Kamren Kinchens",
    "K": "Harrison Mevis"
  },
  "MIA": {
    "QB1": "Malik Willis",
    "QB2": "Quinn Ewers",
    "RB1": "De'Von Achane",
    "RB2": "Jaylen Wright",
    "WR1": "Malik Washington",
    "WR2": "Jalen Tolbert",
    "WR3": "Tutu Atwell",
    "TE1": "Greg Dulcich",
    "TE2": "Ben Sims",
    "LT": "Patrick Paul",
    "LG": "Jonah Savaiinaea",
    "C": "Aaron Brewer",
    "RG": "Jamaree Salyer",
    "RT": "Austin Jackson",
    "DE1": "Chop Robinson",
    "DT1": "Zach Sieler",
    "DT2": "Jordan Phillips",
    "DE2": "Cameron Goode",
    "LB1": "Jordyn Brooks",
    "LB2": "Tyrel Dodson",
    "LB3": "Joshua Uche",
    "CB1": "JuJu Brents",
    "CB2": "Jason Marshall Jr.",
    "NB": "Lonnie Johnson Jr.",
    "SS": "Dante Trader Jr.",
    "FS": "Zayne Anderson",
    "K": "Riley Patterson"
  },
  "MIN": {
    "QB1": "Kyler Murray",
    "QB2": "J.J. McCarthy",
    "RB1": "Aaron Jones Sr.",
    "RB2": "Jordan Mason",
    "WR1": "Justin Jefferson",
    "WR2": "Jordan Addison",
    "WR3": "Tai Felton",
    "TE1": "T.J. Hockenson",
    "TE2": "Josh Oliver",
    "LT": "Christian Darrisaw",
    "LG": "Donovan Jackson",
    "C": "Michael Jurgens",
    "RG": "Will Fries",
    "RT": "Brian O'Neill",
    "DE1": "Levi Drake Rodriguez",
    "DT1": "Jalen Redmond",
    "DE2": "Tyrion Ingram-Dawkins",
    "LB1": "Jonathan Greenard",
    "LB2": "Blake Cashman",
    "LB3": "Eric Wilson",
    "LB4": "Andrew Van Ginkel",
    "CB1": "Isaiah Rodgers",
    "CB2": "Byron Murphy Jr.",
    "NB": "Theo Jackson",
    "SS": "Joshua Metellus",
    "FS": "Jay Ward",
    "K": "Will Reichard"
  },
  "NE": {
    "QB1": "Drake Maye",
    "QB2": "Joshua Dobbs",
    "RB1": "Rhamondre Stevenson",
    "RB2": "TreVeyon Henderson",
    "WR1": "Romeo Doubs",
    "WR2": "Kayshon Boutte",
    "WR3": "Mack Hollins",
    "TE1": "Hunter Henry",
    "TE2": "Julian Hill",
    "LT": "Will Campbell",
    "LG": "Alijah Vera-Tucker",
    "C": "Jared Wilson",
    "RG": "Mike Onwenu",
    "RT": "Morgan Moses",
    "DE1": "Christian Barmore",
    "DT1": "Eric Gregory",
    "DE2": "Milton Williams",
    "LB1": "Robert Spillane",
    "LB2": "Christian Elliss",
    "DT2": "Cory Durden",
    "CB1": "Carlton Davis III",
    "CB2": "Christian Gonzalez",
    "NB": "Marcus Jones",
    "SS": "Craig Woodson",
    "FS": "Kevin Byard III",
    "K": "Andy Borregales"
  },
  "NO": {
    "QB1": "Tyler Shough",
    "QB2": "Spencer Rattler",
    "RB1": "Travis Etienne Jr.",
    "RB2": "Alvin Kamara",
    "WR1": "Chris Olave",
    "WR2": "Devaughn Vele",
    "WR3": "Mason Tipton",
    "TE1": "Juwan Johnson",
    "TE2": "Noah Fant",
    "LT": "Kelvin Banks Jr.",
    "LG": "David Edwards",
    "C": "Erik McCoy",
    "RG": "Cesar Ruiz",
    "RT": "Taliese Fuaga",
    "DE1": "Vernon Broughton",
    "DT1": "Davon Godchaux",
    "DE2": "Bryan Bresee",
    "LB1": "Carl Granderson",
    "LB2": "Kaden Elliss",
    "LB3": "Pete Werner",
    "LB4": "Chase Young",
    "CB1": "Kool-Aid McKinstry",
    "CB2": "Quincy Riley",
    "NB": "Jordan Howden",
    "SS": "Justin Reid",
    "FS": "Julian Blackmon",
    "K": "Charlie Smyth"
  },
  "NYG": {
    "QB1": "Jaxson Dart",
    "QB2": "Jameis Winston",
    "RB1": "Cam Skattebo",
    "RB2": "Tyrone Tracy Jr.",
    "WR1": "Malik Nabers",
    "WR2": "Darius Slayton",
    "WR3": "Darnell Mooney",
    "TE1": "Isaiah Likely",
    "TE2": "Theo Johnson",
    "LT": "Andrew Thomas",
    "LG": "Jon Runyan",
    "C": "John Michael Schmitz Jr.",
    "RG": "Jake Kubas",
    "RT": "Jermaine Eluemunor",
    "DE1": "Darius Alexander",
    "DT1": "Dexter Lawrence II",
    "DE2": "Roy Robertson-Harris",
    "LB1": "Brian Burns",
    "LB2": "Tremaine Edmunds",
    "LB3": "Micah McFadden",
    "LB4": "Kayvon Thibodeaux",
    "CB1": "Paulson Adebo",
    "CB2": "Greg Newsome II",
    "NB": "Dru Phillips",
    "SS": "Tyler Nubin",
    "FS": "Jevon Holland",
    "K": "Jason Sanders"
  },
  "NYJ": {
    "QB1": "Geno Smith",
    "QB2": "Brady Cook",
    "RB1": "Breece Hall",
    "RB2": "Braelon Allen",
    "WR1": "Garrett Wilson",
    "WR2": "Adonai Mitchell",
    "WR3": "Isaiah Williams",
    "TE1": "Mason Taylor",
    "TE2": "Jeremy Ruckert",
    "LT": "Olu Fashanu",
    "LG": "Dylan Parham",
    "C": "Josh Myers",
    "RG": "Joe Tippmann",
    "RT": "Armand Membou",
    "DE1": "Will McDonald IV",
    "DT1": "Harrison Phillips",
    "DT2": "T'Vondre Sweat",
    "DE2": "Joseph Ossai",
    "LB1": "Kiko Mauigoa",
    "LB2": "Demario Davis",
    "LB3": "Kobe King",
    "CB1": "Azareye'h Thomas",
    "CB2": "Brandon Stephens",
    "NB": "Jarvis Brownlee Jr.",
    "SS": "Andre Cisco",
    "FS": "Minkah Fitzpatrick",
    "K": "Cade York"
  },
  "PHI": {
    "QB1": "Jalen Hurts",
    "QB2": "Tanner McKee",
    "RB1": "Saquon Barkley",
    "RB2": "Tank Bigsby",
    "WR1": "A.J. Brown",
    "WR2": "DeVonta Smith",
    "WR3": "Hollywood Brown",
    "TE1": "Dallas Goedert",
    "TE2": "Grant Calcaterra",
    "LT": "Jordan Mailata",
    "LG": "Landon Dickerson",
    "C": "Cam Jurgens",
    "RG": "Tyler Steen",
    "RT": "Lane Johnson",
    "DE1": "Moro Ojomo",
    "DT1": "Jordan Davis",
    "DE2": "Jalen Carter",
    "LB1": "Nolan Smith Jr.",
    "LB2": "Zack Baun",
    "LB3": "Jihaad Campbell",
    "LB4": "Jalyx Hunt",
    "CB1": "Riq Woolen",
    "CB2": "Quinyon Mitchell",
    "NB": "Cooper DeJean",
    "SS": "Sydney Brown",
    "FS": "Andrew Mukuba",
    "K": "Jake Elliott"
  },
  "PIT": {
    "QB1": "Mason Rudolph",
    "QB2": "Will Howard",
    "RB1": "Jaylen Warren",
    "RB2": "Rico Dowdle",
    "WR1": "DK Metcalf",
    "WR2": "Michael Pittman Jr.",
    "WR3": "Roman Wilson",
    "TE1": "Pat Freiermuth",
    "TE2": "Darnell Washington",
    "LT": "Broderick Jones",
    "LG": "Spencer Anderson",
    "C": "Zach Frazier",
    "RG": "Mason McCormick",
    "RT": "Troy Fautanu",
    "DE1": "Cameron Heyward",
    "DT1": "Keeanu Benton",
    "DE2": "Derrick Harmon",
    "LB1": "T.J. Watt",
    "LB2": "Patrick Queen",
    "LB3": "Malik Harrison",
    "LB4": "Alex Highsmith",
    "CB1": "Jamel Dean",
    "CB2": "Joey Porter Jr.",
    "NB": "Jalen Ramsey",
    "SS": "Jaquan Brisker",
    "FS": "DeShon Elliott",
    "K": "Chris Boswell"
  },
  "SF": {
    "QB1": "Brock Purdy",
    "QB2": "Mac Jones",
    "RB1": "Christian McCaffrey",
    "RB2": "Jordan James",
    "WR1": "Mike Evans",
    "WR2": "Ricky Pearsall",
    "WR3": "Christian Kirk",
    "TE1": "George Kittle",
    "TE2": "Jake Tonges",
    "LT": "Trent Williams",
    "LG": "Brett Toth",
    "C": "Jake Brendel",
    "RG": "Dominick Puni",
    "RT": "Colton McKivitz",
    "DE1": "C.J. West",
    "DT1": "Alfred Collins",
    "DE2": "Osa Odighizuwa",
    "LB1": "Nick Bosa",
    "LB2": "Dre Greenlaw",
    "LB3": "Fred Warner",
    "LB4": "Mykel Williams",
    "CB1": "Renardo Green",
    "CB2": "Deommodore Lenoir",
    "NB": "Upton Stout",
    "SS": "Ji'Ayir Brown",
    "FS": "Malik Mustapha",
    "K": "Eddy Pineiro"
  },
  "SEA": {
    "QB1": "Sam Darnold",
    "QB2": "Drew Lock",
    "RB1": "Zach Charbonnet",
    "RB2": "Emanuel Wilson",
    "WR1": "Jaxon Smith-Njigba",
    "WR2": "Cooper Kupp",
    "WR3": "Rashid Shaheed",
    "TE1": "AJ Barner",
    "TE2": "Elijah Arroyo",
    "LT": "Charles Cross",
    "LG": "Grey Zabel",
    "C": "Jalen Sundell",
    "RG": "Anthony Bradford",
    "RT": "Abraham Lucas",
    "DE1": "Leonard Williams",
    "DT1": "Byron Murphy II",
    "DE2": "Jarran Reed",
    "LB1": "Drake Thomas",
    "LB2": "Ernest Jones IV",
    "DT2": "Brandon Pili",
    "CB1": "Devon Witherspoon",
    "CB2": "Josh Jobe",
    "NB": "Nick Emmanwori",
    "SS": "Ty Okada",
    "FS": "Julian Love",
    "K": "Jason Myers"
  },
  "TB": {
    "QB1": "Baker Mayfield",
    "QB2": "Jake Browning",
    "RB1": "Bucky Irving",
    "RB2": "Kenneth Gainwell",
    "WR1": "Chris Godwin Jr.",
    "WR2": "Emeka Egbuka",
    "WR3": "Jalen McMillan",
    "TE1": "Cade Otton",
    "TE2": "Payne Durham",
    "LT": "Tristan Wirfs",
    "LG": "Ben Bredeson",
    "C": "Graham Barton",
    "RG": "Cody Mauch",
    "RT": "Luke Goedeke",
    "DE1": "Al-Quadin Muhammad",
    "DT1": "Vita Vea",
    "DE2": "A'Shawn Robinson",
    "LB1": "Yaya Diaby",
    "LB2": "Alex Anzalone",
    "LB3": "SirVocea Dennis",
    "LB4": "Anthony Nelson",
    "CB1": "Zyon McCollum",
    "CB2": "Benjamin Morrison",
    "NB": "Jacob Parrish",
    "SS": "Tykee Smith",
    "FS": "Antoine Winfield Jr.",
    "K": "Chase McLaughlin"
  },
  "TEN": {
    "QB1": "Cam Ward",
    "QB2": "Mitchell Trubisky",
    "RB1": "Tony Pollard",
    "RB2": "Tyjae Spears",
    "WR1": "Calvin Ridley",
    "WR2": "Wan'Dale Robinson",
    "WR3": "Elic Ayomanor",
    "TE1": "Gunnar Helm",
    "TE2": "Daniel Bellinger",
    "LT": "Dan Moore Jr.",
    "LG": "Peter Skoronski",
    "C": "Austin Schlottmann",
    "RG": "Cordell Volson",
    "RT": "JC Latham",
    "DE1": "Jermaine Johnson",
    "DT1": "Jordan Elliott",
    "DT2": "Jeffery Simmons",
    "DE2": "John Franklin-Myers",
    "LB1": "Cedric Gray",
    "LB2": "Jacob Martin",
    "CB1": "Cor'Dale Flott",
    "CB2": "Micah Robinson",
    "NB": "Alontae Taylor",
    "SS": "Tony Adams",
    "FS": "Kevin Winston Jr.",
    "K": "Joey Slye"
  },
  "WAS": {
    "QB1": "Jayden Daniels",
    "QB2": "Marcus Mariota",
    "RB1": "Jacory Croskey-Merritt",
    "RB2": "Rachaad White",
    "WR1": "Terry McLaurin",
    "WR2": "Luke McCaffrey",
    "WR3": "Treylon Burks",
    "TE1": "Chig Okonkwo",
    "TE2": "John Bates",
    "LT": "Laremy Tunsil",
    "LG": "Chris Paul",
    "C": "Nick Allegretti",
    "RG": "Sam Cosmi",
    "RT": "Josh Conerly Jr.",
    "DE1": "Tim Settle Jr.",
    "DT1": "Daron Payne",
    "DE2": "Javon Kinlaw",
    "LB1": "Odafe Oweh",
    "LB2": "Frankie Luvu",
    "LB3": "Leo Chenal",
    "LB4": "K'Lavon Chaisson",
    "CB1": "Trey Amos",
    "CB2": "Mike Sainristil",
    "NB": "Amik Robertson",
    "SS": "Nick Cross",
    "FS": "Quan Martin",
    "K": "Jake Moody"
  }
};

export default NFL_ROSTERS;
