// Position & trait constants — single source of truth
// Extracted from App.jsx to be importable by any module

export const POSITION_TRAITS={QB:["Arm Strength","Accuracy","Pocket Presence","Mobility","Decision Making","Leadership","Pre-Snap Diagnosis"],RB:["Vision","Contact Balance","Power","Elusiveness","Pass Catching","Speed","Pass Protection"],WR:["Route Running","Separation","Hands","YAC Ability","Speed","Contested Catches","Release Package"],TE:["Receiving","Route Running","Blocking","Athleticism","Hands","Speed"],OT:["Pass Protection","Run Blocking","Footwork","Anchor","Athleticism","Strength"],IOL:["Pass Protection","Run Blocking","Pulling","Strength","Anchor","Versatility"],EDGE:["Pass Rush","Bend","First Step","Power","Motor","Run Defense"],DL:["Pass Rush","Run Defense","First Step","Hand Usage","Motor","Strength"],LB:["Tackling","Coverage","Pass Rush","Instincts","Athleticism","Range","Block Shedding","Pre-Snap Diagnosis"],CB:["Man Coverage","Ball Skills","Zone Coverage","Speed","Press","Nickel"],S:["Man Coverage","Range","Ball Skills","Tackling","Speed","Nickel"],"K/P":["Leg Strength","Accuracy","Consistency","Clutch","Directional Control","Hang Time"]};

export const TRAIT_EMOJI={"Arm Strength":"💪","Accuracy":"🎯","Pocket Presence":"🧊","Mobility":"🏃","Decision Making":"🧠","Leadership":"👑","Vision":"👁️","Contact Balance":"⚖️","Power":"🦬","Elusiveness":"💨","Pass Catching":"🧤","Pass Protection":"🛡️","Route Running":"✂️","Separation":"👻","Hands":"🤲","YAC Ability":"🔥","Speed":"🏎️","Contested Catches":"🏈","Receiving":"🏀","Blocking":"🪵","Athleticism":"🦅","Versatility":"🃏","Run Blocking":"🚜","Footwork":"👟","Anchor":"⚓","Pulling":"🚂","Strength":"🏋️","Pass Rush":"🚀","Bend":"🐍","First Step":"⚡","Hand Usage":"🤚","Motor":"🔥","Run Defense":"🧱","Tackling":"💥","Coverage":"🪂","Man Coverage":"🔒","Zone Coverage":"🗺️","Nickel":"🪙","Instincts":"💡","Range":"📡","Ball Skills":"🧲","Press":"✋","Leg Strength":"🦵","Consistency":"📊","Clutch":"❄️","Directional Control":"🧭","Hang Time":"⏱️","Release Package":"🪽","Block Shedding":"🪓","Pre-Snap Diagnosis":"🔮"};

export const TRAIT_ABBREV={"Arm Strength":"ARM","Accuracy":"ACC","Pocket Presence":"PKT","Mobility":"MOB","Decision Making":"DM","Leadership":"LDR","Vision":"VIS","Contact Balance":"BAL","Power":"PWR","Elusiveness":"ELUS","Pass Catching":"RCV","Speed":"SPD","Route Running":"RR","Separation":"SEP","Hands":"HND","YAC Ability":"YAC","Contested Catches":"CC","Receiving":"RCV","Blocking":"BLK","Athleticism":"ATH","Versatility":"VRS","Run Blocking":"RBK","Footwork":"FT","Anchor":"ANC","Pulling":"PUL","Strength":"STR","Pass Rush":"PR","Bend":"BND","First Step":"1ST","Hand Usage":"HND","Motor":"MTR","Run Defense":"RD","Tackling":"TKL","Coverage":"COV","Man Coverage":"MAN","Zone Coverage":"ZON","Nickel":"NIC","Instincts":"IQ","Range":"RNG","Ball Skills":"BALL","Press":"PRS","Pass Protection":"PP","Release Package":"REL","Block Shedding":"BS","Pre-Snap Diagnosis":"PSD","Leg Strength":"LEG","Consistency":"CON","Clutch":"CLU","Directional Control":"DIR","Hang Time":"HNG"};

export const TRAIT_SHORT={"Contested Catches":"Contested","Man Coverage":"Man Cov","Contact Balance":"Contact Bal","Directional Control":"Directional","Decision Making":"Decision","Pocket Presence":"Pocket Pres","Pass Catching":"Pass Catch","Run Blocking":"Run Block","Pass Protection":"Pass Prot","Hand Usage":"Hand Use","Run Defense":"Run Def","Zone Coverage":"Zone Cov","Leg Strength":"Leg Str","Release Package":"Release","Block Shedding":"Blk Shed","Pre-Snap Diagnosis":"Pre-Snap"};

export const TRAIT_WEIGHTS={QB:{"Accuracy":.25,"Decision Making":.22,"Pocket Presence":.18,"Arm Strength":.15,"Leadership":.09,"Pre-Snap Diagnosis":.08,"Mobility":.03},RB:{"Vision":.22,"Elusiveness":.20,"Contact Balance":.18,"Power":.15,"Speed":.10,"Pass Catching":.09,"Pass Protection":.06},WR:{"Route Running":.25,"Separation":.25,"Hands":.18,"YAC Ability":.16,"Release Package":.08,"Contested Catches":.05,"Speed":.03},TE:{"Receiving":.20,"Blocking":.20,"Route Running":.18,"Hands":.16,"Athleticism":.14,"Speed":.12},OT:{"Pass Protection":.25,"Footwork":.20,"Anchor":.18,"Run Blocking":.15,"Athleticism":.12,"Strength":.10},IOL:{"Run Blocking":.22,"Pass Protection":.22,"Strength":.18,"Pulling":.14,"Anchor":.13,"Versatility":.11},EDGE:{"Pass Rush":.24,"First Step":.20,"Bend":.18,"Power":.15,"Motor":.13,"Run Defense":.10},DL:{"Run Defense":.22,"Pass Rush":.20,"First Step":.18,"Hand Usage":.16,"Motor":.14,"Strength":.10},LB:{"Instincts":.22,"Tackling":.20,"Athleticism":.15,"Coverage":.12,"Pass Rush":.09,"Range":.08,"Pre-Snap Diagnosis":.07,"Block Shedding":.07},CB:{"Man Coverage":.24,"Ball Skills":.20,"Speed":.18,"Press":.15,"Zone Coverage":.13,"Nickel":.10},S:{"Man Coverage":.10,"Range":.25,"Ball Skills":.20,"Tackling":.20,"Speed":.15,"Nickel":.10},"K/P":{"Accuracy":.25,"Leg Strength":.22,"Consistency":.20,"Clutch":.13,"Directional Control":.12,"Hang Time":.08}};

export const TRAIT_TEACHABILITY={"Arm Strength":.1,"Accuracy":.7,"Pocket Presence":.6,"Mobility":.1,"Decision Making":.65,"Leadership":.5,"Vision":.4,"Contact Balance":.2,"Power":.2,"Elusiveness":.15,"Pass Catching":.6,"Pass Protection":.7,"Route Running":.75,"Separation":.5,"Hands":.5,"YAC Ability":.3,"Speed":.05,"Contested Catches":.4,"Receiving":.6,"Blocking":.7,"Athleticism":.05,"Versatility":.3,"Run Blocking":.7,"Footwork":.65,"Anchor":.3,"Pulling":.6,"Strength":.2,"Pass Rush":.4,"Bend":.15,"First Step":.1,"Hand Usage":.65,"Motor":.2,"Run Defense":.6,"Tackling":.6,"Coverage":.5,"Man Coverage":.5,"Zone Coverage":.5,"Nickel":.45,"Instincts":.35,"Range":.1,"Ball Skills":.3,"Press":.55,"Leg Strength":.1,"Consistency":.5,"Clutch":.3,"Directional Control":.6,"Hang Time":.2,"Release Package":.55,"Block Shedding":.45,"Pre-Snap Diagnosis":.6};

export const POSITION_GROUPS=["QB","RB","WR","TE","OT","IOL","EDGE","DL","LB","CB","S","K/P"];

export const POS_EMOJI={QB:"🎯",RB:"🏃",WR:"🧤",TE:"🦾",OT:"🛡️",IOL:"🧱",EDGE:"🌪️",DL:"🦬",LB:"💥",CB:"🏝️",S:"🦅","K/P":"🦵"};

export const POS_COLORS={QB:"#1e3a5f",RB:"#5b21b6",WR:"#0d9488",TE:"#0891b2",OT:"#b45309",IOL:"#d97706",OL:"#b45309",EDGE:"#15803d",DL:"#166534",LB:"#4338ca",CB:"#0f766e",S:"#047857",DB:"#0f766e","K/P":"#78716c"};
